In [12]:
import numpy as np
import pandas as pd
from tqdm import tqdm
import random
import matplotlib.pyplot as plt
import seaborn as sns
import datetime
import os

from sklearn.metrics import roc_auc_score

import pickle
def dump_pkl(data, filename):
  with open(filename, 'wb') as handle:
    pickle.dump(data, handle, protocol=pickle.HIGHEST_PROTOCOL)

def load_pkl(filename):
  with open(filename, 'rb') as handle:
    data = pickle.load(handle)
  return data

In [15]:
!mkdir data data/preproc data/preproc/5min data/preproc/1hour data/preproc/1day

mkdir: data: File exists
mkdir: data/preproc: File exists
mkdir: data/preproc/5min: File exists
mkdir: data/preproc/1hour: File exists
mkdir: data/preproc/1day: File exists

In [30]:
#5min
df_ton = load_pkl('../data/raw/5min/TON-USDT.pkl')
df_near = load_pkl('../data/raw/5min/NEAR-USDT.pkl')
assert (df_ton['time'] == df_near['time']).all(), 'Error'

df = df_ton[['time', 'close']]
df['close'] = df['close'] / df_near['close']
df['ticker'] = 'TON-NEAR'

dump_pkl(df, './data/preproc/5min/TON-NEAR.pkl')

/var/folders/rm/zt5_90s5727289mv2gzbkw980000gn/T/ipykernel_74080/1818930100.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['close'] = df['close'] / df_near['close']
/var/folders/rm/zt5_90s5727289mv2gzbkw980000gn/T/ipykernel_74080/1818930100.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ticker'] = 'TON-NEAR'

In [32]:
#1hour
df_ton = load_pkl('../data/raw/1hour/TON-USDT.pkl')
df_near = load_pkl('../data/raw/1hour/NEAR-USDT.pkl')
assert (df_ton['time'] == df_near['time']).all(), 'Error'

df = df_ton[['time', 'close']]
df['close'] = df['close'] / df_near['close']
df['ticker'] = 'TON-NEAR'

dump_pkl(df, './data/preproc/1hour/TON-NEAR.pkl')

/var/folders/rm/zt5_90s5727289mv2gzbkw980000gn/T/ipykernel_74080/408209045.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['close'] = df['close'] / df_near['close']
/var/folders/rm/zt5_90s5727289mv2gzbkw980000gn/T/ipykernel_74080/408209045.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ticker'] = 'TON-NEAR'

In [34]:
#1day
df_ton = load_pkl('../data/raw/1day/TON-USDT.pkl')
df_near = load_pkl('../data/raw/1day/NEAR-USDT.pkl')
assert (df_ton['time'] == df_near['time']).all(), 'Error'

df = df_ton[['time', 'close']]
df['close'] = df['close'] / df_near['close']
df['ticker'] = 'TON-NEAR'

dump_pkl(df, './data/preproc/1day/TON-NEAR.pkl')

/var/folders/rm/zt5_90s5727289mv2gzbkw980000gn/T/ipykernel_74080/929421145.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['close'] = df['close'] / df_near['close']
/var/folders/rm/zt5_90s5727289mv2gzbkw980000gn/T/ipykernel_74080/929421145.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ticker'] = 'TON-NEAR'

In [39]:
stocks = ['TON-NEAR']

len(stocks)

1

### 1. Load data

In [43]:
dfs_5min = []
dfs_1hour = []
dfs_1day = []

#stocks = [elem.split('.')[0] for elem in os.listdir('./data/preproc/1hour/')]

for stock in tqdm(stocks):

    df_5min = load_pkl(f"./data/preproc/5min/{stock}.pkl")
    df_1hour = load_pkl(f"./data/preproc/1hour/{stock}.pkl")
    df_1day = load_pkl(f"./data/preproc/1day/{stock}.pkl")
    
    dfs_5min += [df_5min.copy()]
    dfs_1hour += [df_1hour.copy()]
    dfs_1day += [df_1day.copy()]
    



df_5min = pd.concat(dfs_5min)
df_1day = pd.concat(dfs_1day)
df_1hour = pd.concat(dfs_1hour)

df_5min.reset_index(drop=True, inplace=True)
df_1hour.reset_index(drop=True, inplace=True)
df_1day.reset_index(drop=True, inplace=True)

df_5min.shape, df_1hour.shape, df_1day.shape

100%|██████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 173.13it/s]

((129312, 3), (10776, 3), (449, 3))

In [45]:
df_5min.head()

                 time     close    ticker
0 2024-01-01 00:00:00  0.616573  TON-NEAR
1 2024-01-01 00:05:00  0.616427  TON-NEAR
2 2024-01-01 00:10:00  0.613775  TON-NEAR
3 2024-01-01 00:15:00  0.608855  TON-NEAR
4 2024-01-01 00:20:00  0.609961  TON-NEAR

In [47]:
df_1hour.head()

                 time     close    ticker
0 2024-01-01 00:00:00  0.625839  TON-NEAR
1 2024-01-01 01:00:00  0.637926  TON-NEAR
2 2024-01-01 02:00:00  0.637784  TON-NEAR
3 2024-01-01 03:00:00  0.620058  TON-NEAR
4 2024-01-01 04:00:00  0.620405  TON-NEAR

In [49]:
df_1day.head()

                 time     close    ticker
0 2024-01-01 03:00:00  0.618771  TON-NEAR
1 2024-01-02 03:00:00  0.585416  TON-NEAR
2 2024-01-03 03:00:00  0.587596  TON-NEAR
3 2024-01-04 03:00:00  0.556295  TON-NEAR
4 2024-01-05 03:00:00  0.587954  TON-NEAR

### 2. Preproc data

#### 2.2 Link data of different time-period

In [56]:
dfs_5min = []
dfs_1hour = []
dfs_1day = []

#stocks = [elem.split('.')[0] for elem in os.listdir('./data/preproc/1hour/')]

for stock in tqdm(stocks):
    df_5min = load_pkl(f"./data/preproc/5min/{stock}.pkl")
    df_1hour = load_pkl(f"./data/preproc/1hour/{stock}.pkl")
    df_1day = load_pkl(f"./data/preproc/1day/{stock}.pkl")

    #time_index 1hour
    df_5min['date_hour_index'] = (df_5min['time'] - pd.Timedelta(minutes=55)).dt.floor('h')
    
    #time_index 1day
    df_5min['date_day_index'] = (df_5min['time'] - pd.Timedelta('26 hours 55 minutes')).dt.floor('d') + pd.Timedelta(hours=3)

    
 
    dfs_5min += [df_5min.copy()]
    dfs_1hour += [df_1hour.copy()]
    dfs_1day += [df_1day.copy()]


df_5min = pd.concat(dfs_5min)
df_1day = pd.concat(dfs_1day)
df_1hour = pd.concat(dfs_1hour)


df_5min.reset_index(drop=True, inplace=True)
df_1hour.reset_index(drop=True, inplace=True)
df_1day.reset_index(drop=True, inplace=True)


df_5min.shape, df_1hour.shape, df_1day.shape

100%|███████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 49.05it/s]

((129312, 5), (10776, 3), (449, 3))

In [58]:
#проверка глазами
i = 68000+13*6 + 12*24*90 - 80
df_5min.iloc[i:i+20]

,time,close,ticker,date_hour_index,date_day_index
93918,2024-11-22 02:30:00,0.953537,TON-NEAR,2024-11-22 01:00:00,2024-11-20 03:00:00
93919,2024-11-22 02:35:00,0.950579,TON-NEAR,2024-11-22 01:00:00,2024-11-20 03:00:00
93920,2024-11-22 02:40:00,0.952332,TON-NEAR,2024-11-22 01:00:00,2024-11-20 03:00:00
93921,2024-11-22 02:45:00,0.952669,TON-NEAR,2024-11-22 01:00:00,2024-11-20 03:00:00
93922,2024-11-22 02:50:00,0.951649,TON-NEAR,2024-11-22 01:00:00,2024-11-20 03:00:00
93923,2024-11-22 02:55:00,0.950950,TON-NEAR,2024-11-22 02:00:00,2024-11-21 03:00:00
93924,2024-11-22 03:00:00,0.947784,TON-NEAR,2024-11-22 02:00:00,2024-11-21 03:00:00
93925,2024-11-22 03:05:00,0.948172,TON-NEAR,2024-11-22 02:00:00,2024-11-21 03:00:00
93926,2024-11-22 03:10:00,0.947486,TON-NEAR,2024-11-22 02:00:00,2024-11-21 03:00:00
93927,2024-11-22 03:15:00,0.945006,TON-NEAR,2024-11-22 02:00:00,2024-11-21 03:00:00
93928,2024-11-22 03:20:00,0.940925,TON-NEAR,2024-11-22 02:00:00,2024-11-21 03:00:00
93929,2024-11-22 03:25:00,0.941327,TON-NEAR,2024-11-22 02:00:00,2024-11-21 03:00:00
93930,2024-11-22 03:30:00,0.948086,TON-NEAR,2024-11-22 02:00:00,2024-11-21 03:00:00
93931,2024-11-22 03:35:00,0.948178,TON-NEAR,2024-11-22 02:00:00,2024-11-21 03:00:00
93932,2024-11-22 03:40:00,0.943084,TON-NEAR,2024-11-22 02:00:00,2024-11-21 03:00:00
93933,2024-11-22 03:45:00,0.945417,TON-NEAR,2024-11-22 02:00:00,2024-11-21 03:00:00
93934,2024-11-22 03:50:00,0.947368,TON-NEAR,2024-11-22 02:00:00,2024-11-21 03:00:00
93935,2024-11-22 03:55:00,0.939087,TON-NEAR,2024-11-22 03:00:00,2024-11-21 03:00:00
93936,2024-11-22 04:00:00,0.941511,TON-NEAR,2024-11-22 03:00:00,2024-11-21 03:00:00
93937,2024-11-22 04:05:00,0.938989,TON-NEAR,2024-11-22 03:00:00,2024-11-21 03:00:00

In [60]:
df_1hour.head()

                 time     close    ticker
0 2024-01-01 00:00:00  0.625839  TON-NEAR
1 2024-01-01 01:00:00  0.637926  TON-NEAR
2 2024-01-01 02:00:00  0.637784  TON-NEAR
3 2024-01-01 03:00:00  0.620058  TON-NEAR
4 2024-01-01 04:00:00  0.620405  TON-NEAR

In [62]:
df_1day.head()

                 time     close    ticker
0 2024-01-01 03:00:00  0.618771  TON-NEAR
1 2024-01-02 03:00:00  0.585416  TON-NEAR
2 2024-01-03 03:00:00  0.587596  TON-NEAR
3 2024-01-04 03:00:00  0.556295  TON-NEAR
4 2024-01-05 03:00:00  0.587954  TON-NEAR

In [68]:
#link different time-step date

df_1hour.reset_index(inplace=True)
df_1hour = df_1hour.rename(columns={col : col+'_1hour' for col in df_1hour.columns if col not in ['ticker']})
df = df_5min.merge(df_1hour, left_on=['date_hour_index', 'ticker'], right_on=['time_1hour', 'ticker'], how='left')

df_1day.reset_index(inplace=True)
df_1day = df_1day.rename(columns={col : col+'_1day' for col in df_1day.columns if col not in ['ticker']})
df = df.merge(df_1day, left_on=['date_day_index', 'ticker'], right_on=['time_1day', 'ticker'], how='left')

#Проверка что не наджоинилось лишнего
assert df_5min.shape[0] == df.shape[0], 'Error: with join dimensions'

In [70]:
df

,time,close,ticker,date_hour_index,date_day_index,index_1hour,time_1hour,close_1hour,index_1day,time_1day,close_1day
0,2024-01-01 00:00:00,0.616573,TON-NEAR,2023-12-31 23:00:00,2023-12-30 03:00:00,NaN,NaT,NaN,NaN,NaT,NaN
1,2024-01-01 00:05:00,0.616427,TON-NEAR,2023-12-31 23:00:00,2023-12-30 03:00:00,NaN,NaT,NaN,NaN,NaT,NaN
2,2024-01-01 00:10:00,0.613775,TON-NEAR,2023-12-31 23:00:00,2023-12-30 03:00:00,NaN,NaT,NaN,NaN,NaT,NaN
3,2024-01-01 00:15:00,0.608855,TON-NEAR,2023-12-31 23:00:00,2023-12-30 03:00:00,NaN,NaT,NaN,NaN,NaT,NaN
4,2024-01-01 00:20:00,0.609961,TON-NEAR,2023-12-31 23:00:00,2023-12-30 03:00:00,NaN,NaT,NaN,NaN,NaT,NaN
...,...,...,...,...,...,...,...,...,...,...,...
129307,2025-03-24 23:35:00,1.255537,TON-NEAR,2025-03-24 22:00:00,2025-03-23 03:00:00,10774.0,2025-03-24 22:00:00,1.256122,447.0,2025-03-23 03:00:00,1.325414
129308,2025-03-24 23:40:00,1.256227,TON-NEAR,2025-03-24 22:00:00,2025-03-23 03:00:00,10774.0,2025-03-24 22:00:00,1.256122,447.0,2025-03-23 03:00:00,1.325414
129309,2025-03-24 23:45:00,1.255036,TON-NEAR,2025-03-24 22:00:00,2025-03-23 03:00:00,10774.0,2025-03-24 22:00:00,1.256122,447.0,2025-03-23 03:00:00,1.325414
129310,2025-03-24 23:50:00,1.255464,TON-NEAR,2025-03-24 22:00:00,2025-03-23 03:00:00,10774.0,2025-03-24 22:00:00,1.256122,447.0,2025-03-23 03:00:00,1.325414
129311,2025-03-24 23:55:00,1.254862,TON-NEAR,2025-03-24 23:00:00,2025-03-23 03:00:00,10775.0,2025-03-24 23:00:00,1.254862,447.0,2025-03-23 03:00:00,1.325414

In [74]:
#Проверка, что данные все данные подтянулись
print(f'Не подтянулсиь пар (ticker, time_1hour) к 5min (от 1hour): {df.loc[df['close_1hour'].isnull(), ['ticker', 'date_hour_index']].groupby(['ticker', 'date_hour_index']).count().shape[0]}  акций-часов')

#Проверка, что данные все данные подтянулись
print(f'Не подтянулсиь пар (ticker, time_1day) к 5min (от 1day): {df.loc[df['close_1day'].isnull(), ['ticker', 'date_day_index']].groupby(['ticker', 'date_day_index']).count().shape[0]}  акций-дней')

Не подтянулсиь пар (ticker, time_1hour) к 5min (от 1hour): 1  акций-часов
Не подтянулсиь пар (ticker, time_1day) к 5min (от 1day): 2  акций-дней

In [77]:
df.loc[df['close_1day'].isnull(), ['ticker', 'date_day_index']].groupby(['ticker', 'date_day_index']).count()

Empty DataFrame
Columns: []
Index: [(TON-NEAR, 2023-12-30 03:00:00), (TON-NEAR, 2023-12-31 03:00:00)]

In [79]:
df['close_1hour'].isnull().mean(), df['close_1day'].isnull().mean()

(8.506557782727047e-05, 0.0024978346943825788)

In [81]:
df['ticker'].nunique()

1

In [83]:
df = df[['time', 'close', 'ticker', 'index_1hour', 'index_1day']]
df

                      time     close    ticker  index_1hour  index_1day
0      2024-01-01 00:00:00  0.616573  TON-NEAR          NaN         NaN
1      2024-01-01 00:05:00  0.616427  TON-NEAR          NaN         NaN
2      2024-01-01 00:10:00  0.613775  TON-NEAR          NaN         NaN
3      2024-01-01 00:15:00  0.608855  TON-NEAR          NaN         NaN
4      2024-01-01 00:20:00  0.609961  TON-NEAR          NaN         NaN
...                    ...       ...       ...          ...         ...
129307 2025-03-24 23:35:00  1.255537  TON-NEAR      10774.0       447.0
129308 2025-03-24 23:40:00  1.256227  TON-NEAR      10774.0       447.0
129309 2025-03-24 23:45:00  1.255036  TON-NEAR      10774.0       447.0
129310 2025-03-24 23:50:00  1.255464  TON-NEAR      10774.0       447.0
129311 2025-03-24 23:55:00  1.254862  TON-NEAR      10775.0       447.0

[129312 rows x 5 columns]

### 2.5 Feature engineering

In [88]:
df

                      time     close    ticker  index_1hour  index_1day
0      2024-01-01 00:00:00  0.616573  TON-NEAR          NaN         NaN
1      2024-01-01 00:05:00  0.616427  TON-NEAR          NaN         NaN
2      2024-01-01 00:10:00  0.613775  TON-NEAR          NaN         NaN
3      2024-01-01 00:15:00  0.608855  TON-NEAR          NaN         NaN
4      2024-01-01 00:20:00  0.609961  TON-NEAR          NaN         NaN
...                    ...       ...       ...          ...         ...
129307 2025-03-24 23:35:00  1.255537  TON-NEAR      10774.0       447.0
129308 2025-03-24 23:40:00  1.256227  TON-NEAR      10774.0       447.0
129309 2025-03-24 23:45:00  1.255036  TON-NEAR      10774.0       447.0
129310 2025-03-24 23:50:00  1.255464  TON-NEAR      10774.0       447.0
129311 2025-03-24 23:55:00  1.254862  TON-NEAR      10775.0       447.0

[129312 rows x 5 columns]

In [90]:
df_1hour.head()

   index_1hour          time_1hour  close_1hour    ticker
0            0 2024-01-01 00:00:00     0.625839  TON-NEAR
1            1 2024-01-01 01:00:00     0.637926  TON-NEAR
2            2 2024-01-01 02:00:00     0.637784  TON-NEAR
3            3 2024-01-01 03:00:00     0.620058  TON-NEAR
4            4 2024-01-01 04:00:00     0.620405  TON-NEAR

In [92]:
df_1day.head()

   index_1day           time_1day  close_1day    ticker
0           0 2024-01-01 03:00:00    0.618771  TON-NEAR
1           1 2024-01-02 03:00:00    0.585416  TON-NEAR
2           2 2024-01-03 03:00:00    0.587596  TON-NEAR
3           3 2024-01-04 03:00:00    0.556295  TON-NEAR
4           4 2024-01-05 03:00:00    0.587954  TON-NEAR

In [96]:
from sklearn.linear_model import LinearRegression

def calculate_exp_ma(data, window):
    alpha = 2 / (window + 1)
    coeffs = ((1 - alpha)**(np.arange(window)[::-1])) * (alpha)
    coeffs[0] /= alpha
    
    return data.rolling(window=window, min_periods=window).apply(lambda x: (x*coeffs).sum()).values


def calculate_bollinger_bands(data, window):
    """Calculate Bollinger Bands"""
    rolling_mean = data.rolling(window=window, min_periods=window).mean().values
    rolling_std = data.rolling(window=window, min_periods=window).std().values
    norm_rolling_std = rolling_std / (rolling_mean + np.finfo(np.float32).eps)

    num_of_std = 2
    lower_band_2std = rolling_mean - (rolling_std * num_of_std)
    upper_band_2std = rolling_mean + (rolling_std * num_of_std)
    
    num_of_std = 3
    lower_band_3std = rolling_mean - (rolling_std * num_of_std)
    upper_band_3std = rolling_mean + (rolling_std * num_of_std)
    
    
    return rolling_mean, rolling_std, norm_rolling_std, lower_band_2std, upper_band_2std, lower_band_3std, upper_band_3std

def calculate_rsi(data, window):
    """Calculate Relative Strength Index"""
    delta = data.diff()
    gain = delta.clip(lower=0)
    loss = -delta.clip(upper=0)
    avg_gain = gain.rolling(window=window, min_periods=window).mean()
    avg_loss = loss.rolling(window=window, min_periods=window).mean()
    rs = avg_gain / avg_loss
    rsi = 100 - (100 / (1 + rs))

    mask = avg_loss == 0
    rsi[mask] = 100
    
    return rsi.values

def calculate_roc(data, periods):
    """Calculate Rate of Change"""
    roc = (data - data.shift(periods)) / (data.shift(periods)+np.finfo(np.float32).eps)
    return roc



def calc_stats(data, window=None, feat_name=None):
    #mean, std
    rolling_mean, rolling_std, norm_rolling_std,\
    lower_band_2std, upper_band_2std, lower_band_3std, upper_band_3std = calculate_bollinger_bands(data, window)

    #mean_abs_pct
    mean_abs_pct = calculate_roc(data, 1).rolling(window=window, min_periods=window).apply(lambda x: x.abs().mean()).values
        
    #alpha
    alpha = data.rolling(window=window, min_periods=window).apply(lambda x: LinearRegression().fit(x.values.reshape(-1, 1), np.arange(x.shape[0])).coef_[0]).values

    #min, max
    rolling_min = data.rolling(window=window, min_periods=window).min().values
    rolling_max = data.rolling(window=window, min_periods=window).max().values
    
    #rsi
    rsi = calculate_rsi(data, window)
    
    #roc
    roc = calculate_roc(data, window).values
    # diff = data.diff(window).values

    #exp_ma
    exp_ma = calculate_exp_ma(data, window)
    
    df_features = pd.DataFrame({f'{feat_name}_ma' : rolling_mean,
                        f'{feat_name}_std' : rolling_std,
                        f'{feat_name}_norm_std' : norm_rolling_std,
                        f'{feat_name}_ma_low_2std' : lower_band_2std,
                        f'{feat_name}_ma_up_2std' : upper_band_2std,
                        f'{feat_name}_ma_low_3std' : lower_band_3std,
                        f'{feat_name}_ma_up_3std' : upper_band_3std, 

                        f'{feat_name}_mean_abs_pct' : mean_abs_pct,
                            
                        f'{feat_name}_alpha' : alpha,
                            
                        f'{feat_name}_min' : rolling_min,
                        f'{feat_name}_max' : rolling_max,
                        f'{feat_name}_rsi' : rsi,
                        f'{feat_name}_roc' : roc,
                        # f'{feat_name}_diff' : diff,
                        f'{feat_name}_expma' : exp_ma,
                        }).astype(np.float32)
    return df_features


def calc_stats_diff_1(data, feat_name=None):
    return pd.DataFrame({f'{feat_name}_roc' : calculate_roc(data, 1).values,
                        # f'{feat_name}_diff' : data.diff(1).values,
                        }).astype(np.float32)

def calc_levels(data, window=None, levels=None, feat_name=None):
    
    #уровни
    data_levels = []
    column_names = []
    for i in range(1, len(levels)):
        level_low = levels[i-1]
        level_high = levels[i]
        data_levels += [data.rolling(window=window, min_periods=window).apply(lambda x: (((1+level_low)*x.values[-1] < x.values) & (x.values <= (1+level_high)*x.values[-1])).sum()).values]
        data_levels += [data.rolling(window=window, min_periods=window).apply(lambda x: (((1-level_high)*x.values[-1] <= x.values) & (x.values < (1-level_low)*x.values[-1])).sum()).values]

        column_names += [f"{feat_name}_lvl_{1+level_low}-{1+level_high}"]
        column_names += [f"{feat_name}_lvl_-{1-level_high}-{1-level_low}"]
    df_levels = pd.DataFrame({column_names[i]:data_levels[i] for i in range(len(column_names))}).astype(np.float32)
    return df_levels

In [99]:
def calculate_features(df_ticker, postfix=None):
    dfs = [df_ticker]
    
    levels =      [0, 0.02, 0.04, 0.06, 0.08, 0.1, 0.12]
    levels_btc =  [0, 0.02, 0.04, 0.06, 0.08, 0.1, 0.12]


    #w1
    df_close = calc_stats_diff_1(df_ticker[f'close{postfix}'], feat_name=f'close{postfix}_w1')
    #df_volume = calc_stats_diff_1(df_ticker[f'volume{postfix}'], feat_name=f'volume{postfix}_w1')
    #df_btc_close = calc_stats_diff_1(df_ticker[f'btc_close{postfix}'], feat_name=f'btc_close{postfix}_w1')
    assert df_ticker.shape[0] == df_close.shape[0], 'Error w1'
    dfs += [df_close.copy()]

    #w5
    window = 5
    df_close = calc_stats(df_ticker[f'close{postfix}'], window=window, feat_name=f'close{postfix}_w{window}')
    #df_volume = calc_stats(df_ticker[f'volume{postfix}'], window=window, feat_name=f'volume{postfix}_w{window}')
    #df_btc_close = calc_stats(df_ticker[f'btc_close{postfix}'], window=window, feat_name=f'btc_close{postfix}_w{window}')
    assert df_ticker.shape[0] == df_close.shape[0], f'Error w{window}'
    dfs += [df_close.copy()]
    
    #w10
    window = 10
    df_close = calc_stats(df_ticker[f'close{postfix}'], window=window, feat_name=f'close{postfix}_w{window}')
    #df_volume = calc_stats(df_ticker[f'volume{postfix}'], window=window, feat_name=f'volume{postfix}_w{window}')
    #df_btc_close = calc_stats(df_ticker[f'btc_close{postfix}'], window=window, feat_name=f'btc_close{postfix}_w{window}')
    assert df_ticker.shape[0] == df_close.shape[0], f'Error w{window}'
    dfs += [df_close.copy()]
    
    #w20
    window = 20
    df_close = calc_stats(df_ticker[f'close{postfix}'], window=window, feat_name=f'close{postfix}_w{window}')
    #df_volume = calc_stats(df_ticker[f'volume{postfix}'], window=window, feat_name=f'volume{postfix}_w{window}')
    #df_btc_close = calc_stats(df_ticker[f'btc_close{postfix}'], window=window, feat_name=f'btc_close{postfix}_w{window}')
    assert df_ticker.shape[0] == df_close.shape[0], f'Error w{window}'
    dfs += [df_close.copy()]
    
    #w30
    window = 30
    df_close = calc_stats(df_ticker[f'close{postfix}'], window=window, feat_name=f'close{postfix}_w{window}')
    #df_volume = calc_stats(df_ticker[f'volume{postfix}'], window=window, feat_name=f'volume{postfix}_w{window}')
    #df_btc_close = calc_stats(df_ticker[f'btc_close{postfix}'], window=window, feat_name=f'btc_close{postfix}_w{window}')
    df_close_levels = calc_levels(df_ticker[f'close{postfix}'], window=window, levels=levels, feat_name=f'close{postfix}_w{window}')
    #df_btc_close_levels = calc_levels(df_ticker[f'btc_close{postfix}'], window=window, levels=levels_btc, feat_name=f'btc_close{postfix}_w{window}')
    assert df_ticker.shape[0] == df_close.shape[0]== df_close_levels.shape[0], f'Error w{window}'
    dfs += [df_close.copy(), df_close_levels.copy()]
    
    #w60
    window = 60
    df_close = calc_stats(df_ticker[f'close{postfix}'], window=window, feat_name=f'close{postfix}_w{window}')
    #df_volume = calc_stats(df_ticker[f'volume{postfix}'], window=window, feat_name=f'volume{postfix}_w{window}')
    #df_btc_close = calc_stats(df_ticker[f'btc_close{postfix}'], window=window, feat_name=f'btc_close{postfix}_w{window}')
    assert df_ticker.shape[0] == df_close.shape[0], f'Error w{window}'
    dfs += [df_close.copy()]
    
    #w120
    window = 120
    df_close = calc_stats(df_ticker[f'close{postfix}'], window=window, feat_name=f'close{postfix}_w{window}')
    #df_volume = calc_stats(df_ticker[f'volume{postfix}'], window=window, feat_name=f'volume{postfix}_w{window}')
    #df_btc_close = calc_stats(df_ticker[f'btc_close{postfix}'], window=window, feat_name=f'btc_close{postfix}_w{window}')
    df_close_levels = calc_levels(df_ticker[f'close{postfix}'], window=window, levels=levels, feat_name=f'close{postfix}_w{window}')
    #df_btc_close_levels = calc_levels(df_ticker[f'btc_close{postfix}'], window=window, levels=levels_btc, feat_name=f'btc_close{postfix}_w{window}')
    assert df_ticker.shape[0] == df_close.shape[0]== df_close_levels.shape[0], f'Error w{window}'
    dfs += [df_close.copy(), df_close_levels.copy()]

   
    df = pd.concat(dfs, axis=1)
    assert (df_ticker.shape[0] == df.shape[0]) and (df.shape[1] == sum([elem.shape[1] for elem in dfs])), 'Error concat'

    return df

#### 5min

In [104]:
dfs = []
for ticker in tqdm(df['ticker'].unique()):
    mask = np.array(df['ticker'] == ticker)
    df_ticker = df.loc[mask].copy().reset_index()

    df_ticker_fe = calculate_features(df_ticker, postfix='')
    #dump_pkl(df_ticker_fe.copy(), f'tmp/{ticker}.pkl', )
    
    dfs += [df_ticker_fe.copy()]

df_fe = pd.concat(dfs).set_index('index')

100%|██████████████████████████████████████████████████████████████████████████| 1/1 [02:25<00:00, 145.92s/it]

In [105]:
(df_fe['close'] == df['close']).all()

True

In [106]:
df_fe.shape

(129312, 114)

In [107]:
df_fe.head()

,time,close,ticker,index_1hour,index_1day,close_w1_roc,close_w5_ma,close_w5_std,close_w5_norm_std,close_w5_ma_low_2std,...,close_w120_lvl_1.02-1.04,close_w120_lvl_-0.96-0.98,close_w120_lvl_1.04-1.06,close_w120_lvl_-0.94-0.96,close_w120_lvl_1.06-1.08,close_w120_lvl_-0.92-0.94,close_w120_lvl_1.08-1.1,close_w120_lvl_-0.9-0.92,close_w120_lvl_1.1-1.12,close_w120_lvl_-0.88-0.9
index,,,,,,,,,,,,,,,,,,,,,
0,2024-01-01 00:00:00,0.616573,TON-NEAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-01-01 00:05:00,0.616427,TON-NEAR,NaN,NaN,-0.000237,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-01-01 00:10:00,0.613775,TON-NEAR,NaN,NaN,-0.004303,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-01-01 00:15:00,0.608855,TON-NEAR,NaN,NaN,-0.008015,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-01-01 00:20:00,0.609961,TON-NEAR,NaN,NaN,0.001816,0.613118,0.003587,0.00585,0.605944,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [109]:
#pd.set_option('display.max_rows', 300)
# df_fe.dtypes

#### 1hour

In [113]:
dfs = []
for ticker in tqdm(df_1hour['ticker'].unique()):
    mask = np.array(df_1hour['ticker'] == ticker)
    df_ticker = df_1hour.loc[mask].copy().reset_index()

    df_ticker_fe = calculate_features(df_ticker, postfix='_1hour')
    
    dfs += [df_ticker_fe.copy()]

df_1hour_fe = pd.concat(dfs).set_index('index')

100%|███████████████████████████████████████████████████████████████████████████| 1/1 [00:12<00:00, 12.16s/it]

In [114]:
(df_1hour_fe['close_1hour'] == df_1hour['close_1hour']).all(), (df_1hour_fe.index.values == df_1hour_fe['index_1hour'].values).all()

(True, True)

In [115]:
df_1hour_fe

,index_1hour,time_1hour,close_1hour,ticker,close_1hour_w1_roc,close_1hour_w5_ma,close_1hour_w5_std,close_1hour_w5_norm_std,close_1hour_w5_ma_low_2std,close_1hour_w5_ma_up_2std,...,close_1hour_w120_lvl_1.02-1.04,close_1hour_w120_lvl_-0.96-0.98,close_1hour_w120_lvl_1.04-1.06,close_1hour_w120_lvl_-0.94-0.96,close_1hour_w120_lvl_1.06-1.08,close_1hour_w120_lvl_-0.92-0.94,close_1hour_w120_lvl_1.08-1.1,close_1hour_w120_lvl_-0.9-0.92,close_1hour_w120_lvl_1.1-1.12,close_1hour_w120_lvl_-0.88-0.9
index,,,,,,,,,,,,,,,,,,,,,
0,0,2024-01-01 00:00:00,0.625839,TON-NEAR,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2024-01-01 01:00:00,0.637926,TON-NEAR,0.019313,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2024-01-01 02:00:00,0.637784,TON-NEAR,-0.000222,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,2024-01-01 03:00:00,0.620058,TON-NEAR,-0.027793,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,2024-01-01 04:00:00,0.620405,TON-NEAR,0.000559,0.628403,0.008929,0.014208,0.610546,0.646260,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10771,10771,2025-03-24 19:00:00,1.269048,TON-NEAR,0.011969,1.252099,0.012614,0.010074,1.226871,1.277327,...,35.0,1.0,47.0,0.0,21.0,0.0,3.0,0.0,0.0,0.0
10772,10772,2025-03-24 20:00:00,1.273842,TON-NEAR,0.003778,1.256952,0.015693,0.012485,1.225565,1.288338,...,43.0,1.0,39.0,0.0,17.0,0.0,2.0,0.0,0.0,0.0
10773,10773,2025-03-24 21:00:00,1.269884,TON-NEAR,-0.003107,1.264171,0.009424,0.007454,1.245324,1.283018,...,36.0,1.0,45.0,0.0,20.0,0.0,3.0,0.0,0.0,0.0
10774,10774,2025-03-24 22:00:00,1.256122,TON-NEAR,-0.010837,1.264587,0.008896,0.007035,1.246795,1.282379,...,12.0,0.0,54.0,0.0,24.0,0.0,13.0,0.0,1.0,0.0
10775,10775,2025-03-24 23:00:00,1.254862,TON-NEAR,-0.001004,1.264752,0.008656,0.006844,1.247440,1.282064,...,12.0,0.0,51.0,0.0,25.0,0.0,14.0,0.0,1.0,0.0

In [116]:
# pd.set_option('display.max_rows', 300)
# df_1hour_fe.dtypes

#### 1day

In [119]:
dfs = []
for ticker in tqdm(df_1day['ticker'].unique()):
    mask = np.array(df_1day['ticker'] == ticker)
    df_ticker = df_1day.loc[mask].copy().reset_index()

    df_ticker_fe = calculate_features(df_ticker, postfix='_1day')
    
    dfs += [df_ticker_fe.copy()]

df_1day_fe = pd.concat(dfs).set_index('index')

100%|███████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.10it/s]

In [120]:
(df_1day_fe['close_1day'] == df_1day['close_1day']).all(), (df_1day_fe.index.values == df_1day_fe['index_1day'].values).all()

(True, True)

In [121]:
df_1day_fe

,index_1day,time_1day,close_1day,ticker,close_1day_w1_roc,close_1day_w5_ma,close_1day_w5_std,close_1day_w5_norm_std,close_1day_w5_ma_low_2std,close_1day_w5_ma_up_2std,...,close_1day_w120_lvl_1.02-1.04,close_1day_w120_lvl_-0.96-0.98,close_1day_w120_lvl_1.04-1.06,close_1day_w120_lvl_-0.94-0.96,close_1day_w120_lvl_1.06-1.08,close_1day_w120_lvl_-0.92-0.94,close_1day_w120_lvl_1.08-1.1,close_1day_w120_lvl_-0.9-0.92,close_1day_w120_lvl_1.1-1.12,close_1day_w120_lvl_-0.88-0.9
index,,,,,,,,,,,,,,,,,,,,,
0,0,2024-01-01 03:00:00,0.618771,TON-NEAR,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2024-01-02 03:00:00,0.585416,TON-NEAR,-0.053907,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2024-01-03 03:00:00,0.587596,TON-NEAR,0.003725,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,2024-01-04 03:00:00,0.556295,TON-NEAR,-0.053270,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,2024-01-05 03:00:00,0.587954,TON-NEAR,0.056911,0.587206,0.022112,0.037657,0.542982,0.631431,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
444,444,2025-03-20 03:00:00,1.352941,TON-NEAR,0.033209,1.342999,0.032817,0.024436,1.277365,1.408633,...,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
445,445,2025-03-21 03:00:00,1.321179,TON-NEAR,-0.023477,1.334052,0.031059,0.023282,1.271933,1.396171,...,3.0,0.0,1.0,0.0,0.0,0.0,0.0,3.0,0.0,3.0
446,446,2025-03-22 03:00:00,1.343098,TON-NEAR,0.016591,1.341157,0.027328,0.020376,1.286501,1.395812,...,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
447,447,2025-03-23 03:00:00,1.325414,TON-NEAR,-0.013166,1.330417,0.017449,0.013116,1.295519,1.365316,...,3.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,5.0
448,448,2025-03-24 03:00:00,1.253507,TON-NEAR,-0.054253,1.319228,0.038948,0.029523,1.241332,1.397123,...,0.0,0.0,4.0,4.0,2.0,6.0,2.0,1.0,1.0,16.0

In [124]:
!mkdir data/feat_engin

mkdir: data/feat_engin: File exists

In [125]:
dump_pkl(df_fe, './data/feat_engin/df_fe.pkl')

In [126]:
dump_pkl(df_1hour_fe, './data/feat_engin/df_1hour_fe.pkl')

In [127]:
dump_pkl(df_1day_fe, './data/feat_engin/df_1day_fe.pkl')

# #Load data

In [134]:
import numpy as np
import pandas as pd
from tqdm import tqdm
import random
import matplotlib.pyplot as plt
import seaborn as sns
import datetime
import os
import gc

from sklearn.metrics import roc_auc_score

import pickle
def dump_pkl(data, filename):
  with open(filename, 'wb') as handle:
    pickle.dump(data, handle, protocol=pickle.HIGHEST_PROTOCOL)

def load_pkl(filename):
  with open(filename, 'rb') as handle:
    data = pickle.load(handle)
  return data

In [135]:
df_fe = load_pkl('./data/feat_engin/df_fe.pkl')
df_1hour_fe = load_pkl('./data/feat_engin/df_1hour_fe.pkl')
df_1day_fe = load_pkl('./data/feat_engin/df_1day_fe.pkl')

df_fe.shape, df_1hour_fe.shape, df_1day_fe.shape,

((129312, 114), (10776, 113), (449, 113))

### time features

In [138]:
#hour
df_fe['hour'] = df_fe['time'].dt.hour

#day
df_fe['day'] = df_fe['time'].dt.day

#day_of_week
df_fe['weekday'] = np.minimum(df_fe['time'].dt.dayofweek, 4) / 4

#month
#df_fe['month'] = df_fe['time'].dt.month


#hour
# time_cyclic = (df_fe['time'] - pd.to_datetime(df_fe['time'].dt.date) - pd.Timedelta('10:00:00')) / pd.Timedelta('13:00:00')
# df_fe['sin_time_hour'] = np.sin(time_cyclic * 2 * np.pi)
# df_fe['cos_time_hour'] = np.cos(time_cyclic * 2 * np.pi)

#day of week
# day_of_week_cyclic = np.minimum(df_fe['time'].dt.dayofweek, 4) / 4
# df_fe['sin_time_weekday'] = np.sin(day_of_week_cyclic * 2 * np.pi)
# df_fe['cos_time_weekday'] = np.cos(day_of_week_cyclic * 2 * np.pi)

#day of month
# day_of_month_cyclic = df_1day_fe['time'].dt.day / 30
# df_1day_fe['sin_time_monthday'] = np.sin(day_of_month_cyclic * 2 * np.pi)
# df_1day_fe['cos_time_monthday'] = np.cos(day_of_month_cyclic * 2 * np.pi)

In [140]:
df_fe.head()

,time,close,ticker,index_1hour,index_1day,close_w1_roc,close_w5_ma,close_w5_std,close_w5_norm_std,close_w5_ma_low_2std,...,close_w120_lvl_-0.94-0.96,close_w120_lvl_1.06-1.08,close_w120_lvl_-0.92-0.94,close_w120_lvl_1.08-1.1,close_w120_lvl_-0.9-0.92,close_w120_lvl_1.1-1.12,close_w120_lvl_-0.88-0.9,hour,day,weekday
index,,,,,,,,,,,,,,,,,,,,,
0,2024-01-01 00:00:00,0.616573,TON-NEAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0.0
1,2024-01-01 00:05:00,0.616427,TON-NEAR,NaN,NaN,-0.000237,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0.0
2,2024-01-01 00:10:00,0.613775,TON-NEAR,NaN,NaN,-0.004303,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0.0
3,2024-01-01 00:15:00,0.608855,TON-NEAR,NaN,NaN,-0.008015,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0.0
4,2024-01-01 00:20:00,0.609961,TON-NEAR,NaN,NaN,0.001816,0.613118,0.003587,0.00585,0.605944,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0.0

In [141]:
df_1hour_fe.head()

,index_1hour,time_1hour,close_1hour,ticker,close_1hour_w1_roc,close_1hour_w5_ma,close_1hour_w5_std,close_1hour_w5_norm_std,close_1hour_w5_ma_low_2std,close_1hour_w5_ma_up_2std,...,close_1hour_w120_lvl_1.02-1.04,close_1hour_w120_lvl_-0.96-0.98,close_1hour_w120_lvl_1.04-1.06,close_1hour_w120_lvl_-0.94-0.96,close_1hour_w120_lvl_1.06-1.08,close_1hour_w120_lvl_-0.92-0.94,close_1hour_w120_lvl_1.08-1.1,close_1hour_w120_lvl_-0.9-0.92,close_1hour_w120_lvl_1.1-1.12,close_1hour_w120_lvl_-0.88-0.9
index,,,,,,,,,,,,,,,,,,,,,
0,0,2024-01-01 00:00:00,0.625839,TON-NEAR,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2024-01-01 01:00:00,0.637926,TON-NEAR,0.019313,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2024-01-01 02:00:00,0.637784,TON-NEAR,-0.000222,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,2024-01-01 03:00:00,0.620058,TON-NEAR,-0.027793,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,2024-01-01 04:00:00,0.620405,TON-NEAR,0.000559,0.628403,0.008929,0.014208,0.610546,0.64626,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [142]:
df_1day_fe.head()

,index_1day,time_1day,close_1day,ticker,close_1day_w1_roc,close_1day_w5_ma,close_1day_w5_std,close_1day_w5_norm_std,close_1day_w5_ma_low_2std,close_1day_w5_ma_up_2std,...,close_1day_w120_lvl_1.02-1.04,close_1day_w120_lvl_-0.96-0.98,close_1day_w120_lvl_1.04-1.06,close_1day_w120_lvl_-0.94-0.96,close_1day_w120_lvl_1.06-1.08,close_1day_w120_lvl_-0.92-0.94,close_1day_w120_lvl_1.08-1.1,close_1day_w120_lvl_-0.9-0.92,close_1day_w120_lvl_1.1-1.12,close_1day_w120_lvl_-0.88-0.9
index,,,,,,,,,,,,,,,,,,,,,
0,0,2024-01-01 03:00:00,0.618771,TON-NEAR,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2024-01-02 03:00:00,0.585416,TON-NEAR,-0.053907,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2024-01-03 03:00:00,0.587596,TON-NEAR,0.003725,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,2024-01-04 03:00:00,0.556295,TON-NEAR,-0.053270,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,2024-01-05 03:00:00,0.587954,TON-NEAR,0.056911,0.587206,0.022112,0.037657,0.542982,0.631431,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Delete useless (dublicated) columns

In [151]:
#del df_1hour_fe['date_hour_index']

In [152]:
#del df_1day_fe['date_index']

### Absolute value columns

In [155]:
def flag_delete(col_name):
    if 'norm_std' in col_name:
        return False
    
    for stop_word in ['ma', 'std', 'diff', 'min', 'max']:
        if stop_word in col_name:
            return True
    return False

In [156]:
cols_del_5min = [elem for elem in df_fe.columns if flag_delete(elem)]
len(cols_del_5min), cols_del_5min

(54,
 ['close_w5_ma',
  'close_w5_std',
  'close_w5_ma_low_2std',
  'close_w5_ma_up_2std',
  'close_w5_ma_low_3std',
  'close_w5_ma_up_3std',
  'close_w5_min',
  'close_w5_max',
  'close_w5_expma',
  'close_w10_ma',
  'close_w10_std',
  'close_w10_ma_low_2std',
  'close_w10_ma_up_2std',
  'close_w10_ma_low_3std',
  'close_w10_ma_up_3std',
  'close_w10_min',
  'close_w10_max',
  'close_w10_expma',
  'close_w20_ma',
  'close_w20_std',
  'close_w20_ma_low_2std',
  'close_w20_ma_up_2std',
  'close_w20_ma_low_3std',
  'close_w20_ma_up_3std',
  'close_w20_min',
  'close_w20_max',
  'close_w20_expma',
  'close_w30_ma',
  'close_w30_std',
  'close_w30_ma_low_2std',
  'close_w30_ma_up_2std',
  'close_w30_ma_low_3std',
  'close_w30_ma_up_3std',
  'close_w30_min',
  'close_w30_max',
  'close_w30_expma',
  'close_w60_ma',
  'close_w60_std',
  'close_w60_ma_low_2std',
  'close_w60_ma_up_2std',
  'close_w60_ma_low_3std',
  'close_w60_ma_up_3std',
  'close_w60_min',
  'close_w60_max',
  'close_w60_expma',
  'close_w120_ma',
  'close_w120_std',
  'close_w120_ma_low_2std',
  'close_w120_ma_up_2std',
  'close_w120_ma_low_3std',
  'close_w120_ma_up_3std',
  'close_w120_min',
  'close_w120_max',
  'close_w120_expma'])

In [157]:
cols_del_1hour = [elem for elem in df_1hour_fe.columns if flag_delete(elem)]
len(cols_del_1hour), cols_del_1hour

(54,
 ['close_1hour_w5_ma',
  'close_1hour_w5_std',
  'close_1hour_w5_ma_low_2std',
  'close_1hour_w5_ma_up_2std',
  'close_1hour_w5_ma_low_3std',
  'close_1hour_w5_ma_up_3std',
  'close_1hour_w5_min',
  'close_1hour_w5_max',
  'close_1hour_w5_expma',
  'close_1hour_w10_ma',
  'close_1hour_w10_std',
  'close_1hour_w10_ma_low_2std',
  'close_1hour_w10_ma_up_2std',
  'close_1hour_w10_ma_low_3std',
  'close_1hour_w10_ma_up_3std',
  'close_1hour_w10_min',
  'close_1hour_w10_max',
  'close_1hour_w10_expma',
  'close_1hour_w20_ma',
  'close_1hour_w20_std',
  'close_1hour_w20_ma_low_2std',
  'close_1hour_w20_ma_up_2std',
  'close_1hour_w20_ma_low_3std',
  'close_1hour_w20_ma_up_3std',
  'close_1hour_w20_min',
  'close_1hour_w20_max',
  'close_1hour_w20_expma',
  'close_1hour_w30_ma',
  'close_1hour_w30_std',
  'close_1hour_w30_ma_low_2std',
  'close_1hour_w30_ma_up_2std',
  'close_1hour_w30_ma_low_3std',
  'close_1hour_w30_ma_up_3std',
  'close_1hour_w30_min',
  'close_1hour_w30_max',
  'close_1hour_w30_expma',
  'close_1hour_w60_ma',
  'close_1hour_w60_std',
  'close_1hour_w60_ma_low_2std',
  'close_1hour_w60_ma_up_2std',
  'close_1hour_w60_ma_low_3std',
  'close_1hour_w60_ma_up_3std',
  'close_1hour_w60_min',
  'close_1hour_w60_max',
  'close_1hour_w60_expma',
  'close_1hour_w120_ma',
  'close_1hour_w120_std',
  'close_1hour_w120_ma_low_2std',
  'close_1hour_w120_ma_up_2std',
  'close_1hour_w120_ma_low_3std',
  'close_1hour_w120_ma_up_3std',
  'close_1hour_w120_min',
  'close_1hour_w120_max',
  'close_1hour_w120_expma'])

In [158]:
cols_del_1day = [elem for elem in df_1day_fe.columns if flag_delete(elem)]
len(cols_del_1day), cols_del_1day

(54,
 ['close_1day_w5_ma',
  'close_1day_w5_std',
  'close_1day_w5_ma_low_2std',
  'close_1day_w5_ma_up_2std',
  'close_1day_w5_ma_low_3std',
  'close_1day_w5_ma_up_3std',
  'close_1day_w5_min',
  'close_1day_w5_max',
  'close_1day_w5_expma',
  'close_1day_w10_ma',
  'close_1day_w10_std',
  'close_1day_w10_ma_low_2std',
  'close_1day_w10_ma_up_2std',
  'close_1day_w10_ma_low_3std',
  'close_1day_w10_ma_up_3std',
  'close_1day_w10_min',
  'close_1day_w10_max',
  'close_1day_w10_expma',
  'close_1day_w20_ma',
  'close_1day_w20_std',
  'close_1day_w20_ma_low_2std',
  'close_1day_w20_ma_up_2std',
  'close_1day_w20_ma_low_3std',
  'close_1day_w20_ma_up_3std',
  'close_1day_w20_min',
  'close_1day_w20_max',
  'close_1day_w20_expma',
  'close_1day_w30_ma',
  'close_1day_w30_std',
  'close_1day_w30_ma_low_2std',
  'close_1day_w30_ma_up_2std',
  'close_1day_w30_ma_low_3std',
  'close_1day_w30_ma_up_3std',
  'close_1day_w30_min',
  'close_1day_w30_max',
  'close_1day_w30_expma',
  'close_1day_w60_ma',
  'close_1day_w60_std',
  'close_1day_w60_ma_low_2std',
  'close_1day_w60_ma_up_2std',
  'close_1day_w60_ma_low_3std',
  'close_1day_w60_ma_up_3std',
  'close_1day_w60_min',
  'close_1day_w60_max',
  'close_1day_w60_expma',
  'close_1day_w120_ma',
  'close_1day_w120_std',
  'close_1day_w120_ma_low_2std',
  'close_1day_w120_ma_up_2std',
  'close_1day_w120_ma_low_3std',
  'close_1day_w120_ma_up_3std',
  'close_1day_w120_min',
  'close_1day_w120_max',
  'close_1day_w120_expma'])

## Concat

In [163]:
df_fe.columns.tolist()

['time',
 'close',
 'ticker',
 'index_1hour',
 'index_1day',
 'close_w1_roc',
 'close_w5_ma',
 'close_w5_std',
 'close_w5_norm_std',
 'close_w5_ma_low_2std',
 'close_w5_ma_up_2std',
 'close_w5_ma_low_3std',
 'close_w5_ma_up_3std',
 'close_w5_mean_abs_pct',
 'close_w5_alpha',
 'close_w5_min',
 'close_w5_max',
 'close_w5_rsi',
 'close_w5_roc',
 'close_w5_expma',
 'close_w10_ma',
 'close_w10_std',
 'close_w10_norm_std',
 'close_w10_ma_low_2std',
 'close_w10_ma_up_2std',
 'close_w10_ma_low_3std',
 'close_w10_ma_up_3std',
 'close_w10_mean_abs_pct',
 'close_w10_alpha',
 'close_w10_min',
 'close_w10_max',
 'close_w10_rsi',
 'close_w10_roc',
 'close_w10_expma',
 'close_w20_ma',
 'close_w20_std',
 'close_w20_norm_std',
 'close_w20_ma_low_2std',
 'close_w20_ma_up_2std',
 'close_w20_ma_low_3std',
 'close_w20_ma_up_3std',
 'close_w20_mean_abs_pct',
 'close_w20_alpha',
 'close_w20_min',
 'close_w20_max',
 'close_w20_rsi',
 'close_w20_roc',
 'close_w20_expma',
 'close_w30_ma',
 'close_w30_std',
 'close_w30_norm_std',
 'close_w30_ma_low_2std',
 'close_w30_ma_up_2std',
 'close_w30_ma_low_3std',
 'close_w30_ma_up_3std',
 'close_w30_mean_abs_pct',
 'close_w30_alpha',
 'close_w30_min',
 'close_w30_max',
 'close_w30_rsi',
 'close_w30_roc',
 'close_w30_expma',
 'close_w30_lvl_1-1.02',
 'close_w30_lvl_-0.98-1',
 'close_w30_lvl_1.02-1.04',
 'close_w30_lvl_-0.96-0.98',
 'close_w30_lvl_1.04-1.06',
 'close_w30_lvl_-0.94-0.96',
 'close_w30_lvl_1.06-1.08',
 'close_w30_lvl_-0.92-0.94',
 'close_w30_lvl_1.08-1.1',
 'close_w30_lvl_-0.9-0.92',
 'close_w30_lvl_1.1-1.12',
 'close_w30_lvl_-0.88-0.9',
 'close_w60_ma',
 'close_w60_std',
 'close_w60_norm_std',
 'close_w60_ma_low_2std',
 'close_w60_ma_up_2std',
 'close_w60_ma_low_3std',
 'close_w60_ma_up_3std',
 'close_w60_mean_abs_pct',
 'close_w60_alpha',
 'close_w60_min',
 'close_w60_max',
 'close_w60_rsi',
 'close_w60_roc',
 'close_w60_expma',
 'close_w120_ma',
 'close_w120_std',
 'close_w120_norm_std',
 'close_w120_ma_low_2std',
 'close_w120_ma_up_2std',
 'close_w120_ma_low_3std',
 'close_w120_ma_up_3std',
 'close_w120_mean_abs_pct',
 'close_w120_alpha',
 'close_w120_min',
 'close_w120_max',
 'close_w120_rsi',
 'close_w120_roc',
 'close_w120_expma',
 'close_w120_lvl_1-1.02',
 'close_w120_lvl_-0.98-1',
 'close_w120_lvl_1.02-1.04',
 'close_w120_lvl_-0.96-0.98',
 'close_w120_lvl_1.04-1.06',
 'close_w120_lvl_-0.94-0.96',
 'close_w120_lvl_1.06-1.08',
 'close_w120_lvl_-0.92-0.94',
 'close_w120_lvl_1.08-1.1',
 'close_w120_lvl_-0.9-0.92',
 'close_w120_lvl_1.1-1.12',
 'close_w120_lvl_-0.88-0.9',
 'hour',
 'day',
 'weekday']

In [164]:
df_1hour_fe.columns.tolist()

['index_1hour',
 'time_1hour',
 'close_1hour',
 'ticker',
 'close_1hour_w1_roc',
 'close_1hour_w5_ma',
 'close_1hour_w5_std',
 'close_1hour_w5_norm_std',
 'close_1hour_w5_ma_low_2std',
 'close_1hour_w5_ma_up_2std',
 'close_1hour_w5_ma_low_3std',
 'close_1hour_w5_ma_up_3std',
 'close_1hour_w5_mean_abs_pct',
 'close_1hour_w5_alpha',
 'close_1hour_w5_min',
 'close_1hour_w5_max',
 'close_1hour_w5_rsi',
 'close_1hour_w5_roc',
 'close_1hour_w5_expma',
 'close_1hour_w10_ma',
 'close_1hour_w10_std',
 'close_1hour_w10_norm_std',
 'close_1hour_w10_ma_low_2std',
 'close_1hour_w10_ma_up_2std',
 'close_1hour_w10_ma_low_3std',
 'close_1hour_w10_ma_up_3std',
 'close_1hour_w10_mean_abs_pct',
 'close_1hour_w10_alpha',
 'close_1hour_w10_min',
 'close_1hour_w10_max',
 'close_1hour_w10_rsi',
 'close_1hour_w10_roc',
 'close_1hour_w10_expma',
 'close_1hour_w20_ma',
 'close_1hour_w20_std',
 'close_1hour_w20_norm_std',
 'close_1hour_w20_ma_low_2std',
 'close_1hour_w20_ma_up_2std',
 'close_1hour_w20_ma_low_3std',
 'close_1hour_w20_ma_up_3std',
 'close_1hour_w20_mean_abs_pct',
 'close_1hour_w20_alpha',
 'close_1hour_w20_min',
 'close_1hour_w20_max',
 'close_1hour_w20_rsi',
 'close_1hour_w20_roc',
 'close_1hour_w20_expma',
 'close_1hour_w30_ma',
 'close_1hour_w30_std',
 'close_1hour_w30_norm_std',
 'close_1hour_w30_ma_low_2std',
 'close_1hour_w30_ma_up_2std',
 'close_1hour_w30_ma_low_3std',
 'close_1hour_w30_ma_up_3std',
 'close_1hour_w30_mean_abs_pct',
 'close_1hour_w30_alpha',
 'close_1hour_w30_min',
 'close_1hour_w30_max',
 'close_1hour_w30_rsi',
 'close_1hour_w30_roc',
 'close_1hour_w30_expma',
 'close_1hour_w30_lvl_1-1.02',
 'close_1hour_w30_lvl_-0.98-1',
 'close_1hour_w30_lvl_1.02-1.04',
 'close_1hour_w30_lvl_-0.96-0.98',
 'close_1hour_w30_lvl_1.04-1.06',
 'close_1hour_w30_lvl_-0.94-0.96',
 'close_1hour_w30_lvl_1.06-1.08',
 'close_1hour_w30_lvl_-0.92-0.94',
 'close_1hour_w30_lvl_1.08-1.1',
 'close_1hour_w30_lvl_-0.9-0.92',
 'close_1hour_w30_lvl_1.1-1.12',
 'close_1hour_w30_lvl_-0.88-0.9',
 'close_1hour_w60_ma',
 'close_1hour_w60_std',
 'close_1hour_w60_norm_std',
 'close_1hour_w60_ma_low_2std',
 'close_1hour_w60_ma_up_2std',
 'close_1hour_w60_ma_low_3std',
 'close_1hour_w60_ma_up_3std',
 'close_1hour_w60_mean_abs_pct',
 'close_1hour_w60_alpha',
 'close_1hour_w60_min',
 'close_1hour_w60_max',
 'close_1hour_w60_rsi',
 'close_1hour_w60_roc',
 'close_1hour_w60_expma',
 'close_1hour_w120_ma',
 'close_1hour_w120_std',
 'close_1hour_w120_norm_std',
 'close_1hour_w120_ma_low_2std',
 'close_1hour_w120_ma_up_2std',
 'close_1hour_w120_ma_low_3std',
 'close_1hour_w120_ma_up_3std',
 'close_1hour_w120_mean_abs_pct',
 'close_1hour_w120_alpha',
 'close_1hour_w120_min',
 'close_1hour_w120_max',
 'close_1hour_w120_rsi',
 'close_1hour_w120_roc',
 'close_1hour_w120_expma',
 'close_1hour_w120_lvl_1-1.02',
 'close_1hour_w120_lvl_-0.98-1',
 'close_1hour_w120_lvl_1.02-1.04',
 'close_1hour_w120_lvl_-0.96-0.98',
 'close_1hour_w120_lvl_1.04-1.06',
 'close_1hour_w120_lvl_-0.94-0.96',
 'close_1hour_w120_lvl_1.06-1.08',
 'close_1hour_w120_lvl_-0.92-0.94',
 'close_1hour_w120_lvl_1.08-1.1',
 'close_1hour_w120_lvl_-0.9-0.92',
 'close_1hour_w120_lvl_1.1-1.12',
 'close_1hour_w120_lvl_-0.88-0.9']

In [165]:
df_1day_fe.columns.tolist()

['index_1day',
 'time_1day',
 'close_1day',
 'ticker',
 'close_1day_w1_roc',
 'close_1day_w5_ma',
 'close_1day_w5_std',
 'close_1day_w5_norm_std',
 'close_1day_w5_ma_low_2std',
 'close_1day_w5_ma_up_2std',
 'close_1day_w5_ma_low_3std',
 'close_1day_w5_ma_up_3std',
 'close_1day_w5_mean_abs_pct',
 'close_1day_w5_alpha',
 'close_1day_w5_min',
 'close_1day_w5_max',
 'close_1day_w5_rsi',
 'close_1day_w5_roc',
 'close_1day_w5_expma',
 'close_1day_w10_ma',
 'close_1day_w10_std',
 'close_1day_w10_norm_std',
 'close_1day_w10_ma_low_2std',
 'close_1day_w10_ma_up_2std',
 'close_1day_w10_ma_low_3std',
 'close_1day_w10_ma_up_3std',
 'close_1day_w10_mean_abs_pct',
 'close_1day_w10_alpha',
 'close_1day_w10_min',
 'close_1day_w10_max',
 'close_1day_w10_rsi',
 'close_1day_w10_roc',
 'close_1day_w10_expma',
 'close_1day_w20_ma',
 'close_1day_w20_std',
 'close_1day_w20_norm_std',
 'close_1day_w20_ma_low_2std',
 'close_1day_w20_ma_up_2std',
 'close_1day_w20_ma_low_3std',
 'close_1day_w20_ma_up_3std',
 'close_1day_w20_mean_abs_pct',
 'close_1day_w20_alpha',
 'close_1day_w20_min',
 'close_1day_w20_max',
 'close_1day_w20_rsi',
 'close_1day_w20_roc',
 'close_1day_w20_expma',
 'close_1day_w30_ma',
 'close_1day_w30_std',
 'close_1day_w30_norm_std',
 'close_1day_w30_ma_low_2std',
 'close_1day_w30_ma_up_2std',
 'close_1day_w30_ma_low_3std',
 'close_1day_w30_ma_up_3std',
 'close_1day_w30_mean_abs_pct',
 'close_1day_w30_alpha',
 'close_1day_w30_min',
 'close_1day_w30_max',
 'close_1day_w30_rsi',
 'close_1day_w30_roc',
 'close_1day_w30_expma',
 'close_1day_w30_lvl_1-1.02',
 'close_1day_w30_lvl_-0.98-1',
 'close_1day_w30_lvl_1.02-1.04',
 'close_1day_w30_lvl_-0.96-0.98',
 'close_1day_w30_lvl_1.04-1.06',
 'close_1day_w30_lvl_-0.94-0.96',
 'close_1day_w30_lvl_1.06-1.08',
 'close_1day_w30_lvl_-0.92-0.94',
 'close_1day_w30_lvl_1.08-1.1',
 'close_1day_w30_lvl_-0.9-0.92',
 'close_1day_w30_lvl_1.1-1.12',
 'close_1day_w30_lvl_-0.88-0.9',
 'close_1day_w60_ma',
 'close_1day_w60_std',
 'close_1day_w60_norm_std',
 'close_1day_w60_ma_low_2std',
 'close_1day_w60_ma_up_2std',
 'close_1day_w60_ma_low_3std',
 'close_1day_w60_ma_up_3std',
 'close_1day_w60_mean_abs_pct',
 'close_1day_w60_alpha',
 'close_1day_w60_min',
 'close_1day_w60_max',
 'close_1day_w60_rsi',
 'close_1day_w60_roc',
 'close_1day_w60_expma',
 'close_1day_w120_ma',
 'close_1day_w120_std',
 'close_1day_w120_norm_std',
 'close_1day_w120_ma_low_2std',
 'close_1day_w120_ma_up_2std',
 'close_1day_w120_ma_low_3std',
 'close_1day_w120_ma_up_3std',
 'close_1day_w120_mean_abs_pct',
 'close_1day_w120_alpha',
 'close_1day_w120_min',
 'close_1day_w120_max',
 'close_1day_w120_rsi',
 'close_1day_w120_roc',
 'close_1day_w120_expma',
 'close_1day_w120_lvl_1-1.02',
 'close_1day_w120_lvl_-0.98-1',
 'close_1day_w120_lvl_1.02-1.04',
 'close_1day_w120_lvl_-0.96-0.98',
 'close_1day_w120_lvl_1.04-1.06',
 'close_1day_w120_lvl_-0.94-0.96',
 'close_1day_w120_lvl_1.06-1.08',
 'close_1day_w120_lvl_-0.92-0.94',
 'close_1day_w120_lvl_1.08-1.1',
 'close_1day_w120_lvl_-0.9-0.92',
 'close_1day_w120_lvl_1.1-1.12',
 'close_1day_w120_lvl_-0.88-0.9']

In [167]:
df_fe.shape, df_1hour_fe.shape, df_1day_fe.shape

((129312, 117), (10776, 113), (449, 113))

In [168]:
df = df_fe.merge(df_1hour_fe, on=['index_1hour', 'ticker'], how='left')
df.shape

(129312, 228)

In [169]:
df = df.merge(df_1day_fe, on=['index_1day', 'ticker'], how='left')
df.shape

(129312, 339)

In [170]:
df

,time,close,ticker,index_1hour,index_1day,close_w1_roc,close_w5_ma,close_w5_std,close_w5_norm_std,close_w5_ma_low_2std,...,close_1day_w120_lvl_1.02-1.04,close_1day_w120_lvl_-0.96-0.98,close_1day_w120_lvl_1.04-1.06,close_1day_w120_lvl_-0.94-0.96,close_1day_w120_lvl_1.06-1.08,close_1day_w120_lvl_-0.92-0.94,close_1day_w120_lvl_1.08-1.1,close_1day_w120_lvl_-0.9-0.92,close_1day_w120_lvl_1.1-1.12,close_1day_w120_lvl_-0.88-0.9
0,2024-01-01 00:00:00,0.616573,TON-NEAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-01-01 00:05:00,0.616427,TON-NEAR,NaN,NaN,-0.000237,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-01-01 00:10:00,0.613775,TON-NEAR,NaN,NaN,-0.004303,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-01-01 00:15:00,0.608855,TON-NEAR,NaN,NaN,-0.008015,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-01-01 00:20:00,0.609961,TON-NEAR,NaN,NaN,0.001816,0.613118,0.003587,0.005850,0.605944,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129307,2025-03-24 23:35:00,1.255537,TON-NEAR,10774.0,447.0,0.000415,1.256682,0.001923,0.001530,1.252836,...,3.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,5.0
129308,2025-03-24 23:40:00,1.256227,TON-NEAR,10774.0,447.0,0.000549,1.256022,0.001089,0.000867,1.253844,...,3.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,5.0
129309,2025-03-24 23:45:00,1.255036,TON-NEAR,10774.0,447.0,-0.000948,1.255467,0.000494,0.000393,1.254480,...,3.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,5.0
129310,2025-03-24 23:50:00,1.255464,TON-NEAR,10774.0,447.0,0.000342,1.255456,0.000493,0.000392,1.254470,...,3.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,5.0
129311,2025-03-24 23:55:00,1.254862,TON-NEAR,10775.0,447.0,-0.000480,1.255425,0.000530,0.000422,1.254364,...,3.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,5.0

In [172]:
df.loc[df['index_1hour'].isnull(), 'time'].dt.date.unique()

array([datetime.date(2024, 1, 1)], dtype=object)

In [173]:
df.loc[df['index_1day'].isnull(), 'time'].dt.date.unique()

array([datetime.date(2024, 1, 1), datetime.date(2024, 1, 2)], dtype=object)

In [175]:
# for col in tqdm(df.columns):
#     assert df[col].isnull().sum() == 0, f'Nulls {col}'
#     # if df[col].isnull().sum() != 0:
#     #     print(col, df[col].isnull().sum())

In [179]:
#df.loc[df['volume_w1_roc'].isnull()]

### Relative features

In [183]:
groups_5min = [
        #windows: 
        #close: w1, w5, w10, w20, w30, w60, w120
        #volume: w1, w5, w10, w20
        #btc_close: w1, w5, w10, w20, w30, w60, w120
         ['close_w1_roc', 'close_w5_alpha', 'close_w10_alpha', 'close_w20_alpha', 'close_w30_alpha', 'close_w60_alpha', 'close_w120_alpha'],
         #['volume_w1_roc', 'volume_w5_alpha', 'volume_w10_alpha'],
         #['btc_close_w1_roc', 'btc_close_w5_alpha', 'btc_close_w10_alpha', 'btc_close_w20_alpha', 'btc_close_w30_alpha', 'btc_close_w60_alpha', 'btc_close_w120_alpha'],
    
    
         ['close_w1_roc', 'close_w5_roc', 'close_w10_roc', 'close_w20_roc', 'close_w30_roc', 'close_w60_roc', 'close_w120_roc'],
         #['volume_w1_roc', 'volume_w5_roc', 'volume_w10_roc'],
         #['btc_close_w1_roc', 'btc_close_w5_roc', 'btc_close_w10_roc', 'btc_close_w20_roc', 'btc_close_w30_roc', 'btc_close_w60_roc', 'btc_close_w120_roc'],

    
         ['close_w5_mean_abs_pct', 'close_w10_mean_abs_pct', 'close_w20_mean_abs_pct', 'close_w30_mean_abs_pct', 'close_w60_mean_abs_pct', 'close_w120_mean_abs_pct'],
         #['volume_w5_mean_abs_pct', 'volume_w10_mean_abs_pct'],
         #['btc_close_w5_mean_abs_pct', 'btc_close_w10_mean_abs_pct', 'btc_close_w20_mean_abs_pct', 'btc_close_w30_mean_abs_pct', 'btc_close_w60_mean_abs_pct', 'btc_close_w120_mean_abs_pct'],


         ['close_w5_std', 'close_w10_std', 'close_w20_std', 'close_w30_std', 'close_w60_std', 'close_w120_std'],
         #['volume_w5_std', 'volume_w10_std'],
         #['btc_close_w5_std', 'btc_close_w10_std', 'btc_close_w20_std', 'btc_close_w30_std', 'btc_close_w60_std', 'btc_close_w120_std'],


         ['close_w5_norm_std', 'close_w10_norm_std', 'close_w20_norm_std', 'close_w30_norm_std', 'close_w60_norm_std', 'close_w120_norm_std'],
         #['volume_w5_norm_std', 'volume_w10_norm_std'],
         #['btc_close_w5_norm_std', 'btc_close_w10_norm_std', 'btc_close_w20_norm_std', 'btc_close_w30_norm_std', 'btc_close_w60_norm_std', 'btc_close_w120_norm_std'],


         ['close_w5_rsi', 'close_w10_rsi', 'close_w20_rsi', 'close_w30_rsi', 'close_w60_rsi', 'close_w120_rsi'],
         #['volume_w5_rsi', 'volume_w10_rsi'],
         #['btc_close_w5_rsi', 'btc_close_w10_rsi', 'btc_close_w20_rsi', 'btc_close_w30_rsi', 'btc_close_w60_rsi', 'btc_close_w120_rsi'],


         ['close', 'close_w5_ma', 'close_w10_ma', 'close_w20_ma', 'close_w30_ma', 'close_w60_ma', 'close_w120_ma'],
         #['volume', 'volume_w5_ma', 'volume_w10_ma'],
         #['btc_close', 'btc_close_w5_ma', 'btc_close_w10_ma', 'btc_close_w20_ma', 'btc_close_w30_ma', 'btc_close_w60_ma', 'btc_close_w120_ma'],


         ['close', 'close_w5_expma', 'close_w10_expma', 'close_w20_expma', 'close_w30_expma', 'close_w60_expma', 'close_w120_expma'],
         #['volume', 'volume_w5_expma', 'volume_w10_expma'],
         #['btc_close', 'btc_close_w5_expma', 'btc_close_w10_expma', 'btc_close_w20_expma', 'btc_close_w30_expma', 'btc_close_w60_expma', 'btc_close_w120_expma'],


         {'close' : ['close_w5_min', 'close_w10_min', 'close_w20_min', 'close_w30_min', 'close_w60_min', 'close_w120_min']},
         #{'volume' : ['volume_w5_min', 'volume_w10_min']},
         #{'btc_close' : ['btc_close_w5_min', 'btc_close_w10_min', 'btc_close_w20_min', 'btc_close_w30_min', 'btc_close_w60_min', 'btc_close_w120_min']},

    
         {'close' : ['close_w5_max', 'close_w10_max', 'close_w20_max', 'close_w30_max', 'close_w60_max', 'close_w120_max']},
         #{'volume' : ['volume_w5_max', 'volume_w10_max']},
         #{'btc_close' : ['btc_close_w5_max', 'btc_close_w10_max', 'btc_close_w20_max', 'btc_close_w30_max', 'btc_close_w60_max', 'btc_close_w120_max']},



        #w5
         {'close' : [  'close_w5_ma_low_2std', 'close_w5_ma_up_2std', 'close_w5_ma_low_3std', 'close_w5_ma_up_3std']},
         #{'volume' : [  'volume_w5_ma_low_2std', 'volume_w5_ma_up_2std', 'volume_w5_ma_low_3std', 'volume_w5_ma_up_3std']},
         #{'btc_close' : [  'btc_close_w5_ma_low_2std', 'btc_close_w5_ma_up_2std', 'btc_close_w5_ma_low_3std', 'btc_close_w5_ma_up_3std']},
        #w10
         {'close' : [  'close_w10_ma_low_2std', 'close_w10_ma_up_2std', 'close_w10_ma_low_3std', 'close_w10_ma_up_3std']},
         #{'volume' : [  'volume_w10_ma_low_2std', 'volume_w10_ma_up_2std', 'volume_w10_ma_low_3std', 'volume_w10_ma_up_3std']},
         #{'btc_close' : [  'btc_close_w10_ma_low_2std', 'btc_close_w10_ma_up_2std', 'btc_close_w10_ma_low_3std', 'btc_close_w10_ma_up_3std']},
        #w20
         {'close' : [  'close_w20_ma_low_2std', 'close_w20_ma_up_2std', 'close_w20_ma_low_3std', 'close_w20_ma_up_3std']},
         #{'btc_close' : [  'btc_close_w20_ma_low_2std', 'btc_close_w20_ma_up_2std', 'btc_close_w20_ma_low_3std', 'btc_close_w20_ma_up_3std']},
        #w30
         {'close' : [  'close_w30_ma_low_2std', 'close_w30_ma_up_2std', 'close_w30_ma_low_3std', 'close_w30_ma_up_3std']},
         #{'btc_close' : [  'btc_close_w30_ma_low_2std', 'btc_close_w30_ma_up_2std', 'btc_close_w30_ma_low_3std', 'btc_close_w30_ma_up_3std']},
        #w60
         {'close' : [  'close_w60_ma_low_2std', 'close_w60_ma_up_2std', 'close_w60_ma_low_3std', 'close_w60_ma_up_3std']},
         #{'btc_close' : [  'btc_close_w60_ma_low_2std', 'btc_close_w60_ma_up_2std', 'btc_close_w60_ma_low_3std', 'btc_close_w60_ma_up_3std']},
        #w120
         {'close' : [  'close_w120_ma_low_2std', 'close_w120_ma_up_2std', 'close_w120_ma_low_3std', 'close_w120_ma_up_3std']},
         #{'btc_close' : [  'btc_close_w120_ma_low_2std', 'btc_close_w120_ma_up_2std', 'btc_close_w120_ma_low_3std', 'btc_close_w120_ma_up_3std']},


        #w5
        ['close_w5_min', 'close_w5_max'],
        #['volume_w5_min', 'volume_w5_max'],
        #['btc_close_w5_min', 'btc_close_w5_max'],
        #w10
        ['close_w10_min', 'close_w10_max'],
        #['volume_w10_min', 'volume_w10_max'],
        #['btc_close_w10_min', 'btc_close_w10_max'],
        #w20
        ['close_w20_min', 'close_w20_max'],
        #['btc_close_w20_min', 'btc_close_w20_max'],
        #w30
        ['close_w30_min', 'close_w30_max'],
        #['btc_close_w30_min', 'btc_close_w30_max'],
        #w60
        ['close_w60_min', 'close_w60_max'],
        #['btc_close_w60_min', 'btc_close_w60_max'],
        #w120
        ['close_w120_min', 'close_w120_max'],
        #['btc_close_w120_min', 'btc_close_w120_max'],
]

In [184]:
groups_1hour = [
        #windows: 
        #close: w1, w5, w10, w20, w30, w60, w120
        #volume: w1, w5, w10, w20
        #btc_close: w1, w5, w10, w20, w30, w60, w120
         ['close_1hour_w1_roc', 'close_1hour_w5_alpha', 'close_1hour_w10_alpha', 'close_1hour_w20_alpha', 'close_1hour_w30_alpha', 'close_1hour_w60_alpha', 'close_1hour_w120_alpha'],
         #['volume_1hour_w1_roc', 'volume_1hour_w5_alpha', 'volume_1hour_w10_alpha'],
         #['btc_close_1hour_w1_roc', 'btc_close_1hour_w5_alpha', 'btc_close_1hour_w10_alpha', 'btc_close_1hour_w20_alpha', 'btc_close_1hour_w30_alpha', 'btc_close_1hour_w60_alpha', 'btc_close_1hour_w120_alpha'],
    
         ['close_1hour_w1_roc', 'close_1hour_w5_roc', 'close_1hour_w10_roc', 'close_1hour_w20_roc', 'close_1hour_w30_roc', 'close_1hour_w60_roc', 'close_1hour_w120_roc'],
         #['volume_1hour_w1_roc', 'volume_1hour_w5_roc', 'volume_1hour_w10_roc'],
         #['btc_close_1hour_w1_roc', 'btc_close_1hour_w5_roc', 'btc_close_1hour_w10_roc', 'btc_close_1hour_w20_roc', 'btc_close_1hour_w30_roc', 'btc_close_1hour_w60_roc', 'btc_close_1hour_w120_roc'],

         ['close_1hour_w5_mean_abs_pct', 'close_1hour_w10_mean_abs_pct', 'close_1hour_w20_mean_abs_pct', 'close_1hour_w30_mean_abs_pct', 'close_1hour_w60_mean_abs_pct', 'close_1hour_w120_mean_abs_pct'],
         #['volume_1hour_w5_mean_abs_pct', 'volume_1hour_w10_mean_abs_pct'],
         #['btc_close_1hour_w5_mean_abs_pct', 'btc_close_1hour_w10_mean_abs_pct', 'btc_close_1hour_w20_mean_abs_pct', 'btc_close_1hour_w30_mean_abs_pct', 'btc_close_1hour_w60_mean_abs_pct', 'btc_close_1hour_w120_mean_abs_pct'],


         ['close_1hour_w5_std', 'close_1hour_w10_std', 'close_1hour_w20_std', 'close_1hour_w30_std', 'close_1hour_w60_std', 'close_1hour_w120_std'],
         #['volume_1hour_w5_std', 'volume_1hour_w10_std'],
         #['btc_close_1hour_w5_std', 'btc_close_1hour_w10_std', 'btc_close_1hour_w20_std', 'btc_close_1hour_w30_std', 'btc_close_1hour_w60_std', 'btc_close_1hour_w120_std'],


         ['close_1hour_w5_norm_std', 'close_1hour_w10_norm_std', 'close_1hour_w20_norm_std', 'close_1hour_w30_norm_std', 'close_1hour_w60_norm_std', 'close_1hour_w120_norm_std'],
         #['volume_1hour_w5_norm_std', 'volume_1hour_w10_norm_std'],
         #['btc_close_1hour_w5_norm_std', 'btc_close_1hour_w10_norm_std', 'btc_close_1hour_w20_norm_std', 'btc_close_1hour_w30_norm_std', 'btc_close_1hour_w60_norm_std', 'btc_close_1hour_w120_norm_std'],


         ['close_1hour_w5_rsi', 'close_1hour_w10_rsi', 'close_1hour_w20_rsi', 'close_1hour_w30_rsi', 'close_1hour_w60_rsi', 'close_1hour_w120_rsi'],
         #['volume_1hour_w5_rsi', 'volume_1hour_w10_rsi'],
         #['btc_close_1hour_w5_rsi', 'btc_close_1hour_w10_rsi', 'btc_close_1hour_w20_rsi', 'btc_close_1hour_w30_rsi', 'btc_close_1hour_w60_rsi', 'btc_close_1hour_w120_rsi'],


         ['close', 'close_1hour_w5_ma', 'close_1hour_w10_ma', 'close_1hour_w20_ma', 'close_1hour_w30_ma', 'close_1hour_w60_ma', 'close_1hour_w120_ma'],
         #['volume', 'volume_1hour_w5_ma', 'volume_1hour_w10_ma'],
         #['btc_close', 'btc_close_1hour_w5_ma', 'btc_close_1hour_w10_ma', 'btc_close_1hour_w20_ma', 'btc_close_1hour_w30_ma', 'btc_close_1hour_w60_ma', 'btc_close_1hour_w120_ma'],


         ['close', 'close_1hour_w5_expma', 'close_1hour_w10_expma', 'close_1hour_w20_expma', 'close_1hour_w30_expma', 'close_1hour_w60_expma', 'close_1hour_w120_expma'],
         #['volume', 'volume_1hour_w5_expma', 'volume_1hour_w10_expma'],
         #['btc_close', 'btc_close_1hour_w5_expma', 'btc_close_1hour_w10_expma', 'btc_close_1hour_w20_expma', 'btc_close_1hour_w30_expma', 'btc_close_1hour_w60_expma', 'btc_close_1hour_w120_expma'],


         {'close' : ['close_1hour_w5_min', 'close_1hour_w10_min', 'close_1hour_w20_min', 'close_1hour_w30_min', 'close_1hour_w60_min', 'close_1hour_w120_min']},
         #{'volume' : ['volume_1hour_w5_min', 'volume_1hour_w10_min']},
         #{'btc_close' : ['btc_close_1hour_w5_min', 'btc_close_1hour_w10_min', 'btc_close_1hour_w20_min', 'btc_close_1hour_w30_min', 'btc_close_1hour_w60_min', 'btc_close_1hour_w120_min']},

    
         {'close' : ['close_1hour_w5_max', 'close_1hour_w10_max', 'close_1hour_w20_max', 'close_1hour_w30_max', 'close_1hour_w60_max', 'close_1hour_w120_max']},
         #{'volume' : ['volume_1hour_w5_max', 'volume_1hour_w10_max']},
         #{'btc_close' : ['btc_close_1hour_w5_max', 'btc_close_1hour_w10_max', 'btc_close_1hour_w20_max', 'btc_close_1hour_w30_max', 'btc_close_1hour_w60_max', 'btc_close_1hour_w120_max']},



        #w5
         {'close' : [  'close_1hour_w5_ma_low_2std', 'close_1hour_w5_ma_up_2std', 'close_1hour_w5_ma_low_3std', 'close_1hour_w5_ma_up_3std']},
         #{'volume' : [  'volume_1hour_w5_ma_low_2std', 'volume_1hour_w5_ma_up_2std', 'volume_1hour_w5_ma_low_3std', 'volume_1hour_w5_ma_up_3std']},
         #{'btc_close' : [  'btc_close_1hour_w5_ma_low_2std', 'btc_close_1hour_w5_ma_up_2std', 'btc_close_1hour_w5_ma_low_3std', 'btc_close_1hour_w5_ma_up_3std']},
        #w10
         {'close' : [  'close_1hour_w10_ma_low_2std', 'close_1hour_w10_ma_up_2std', 'close_1hour_w10_ma_low_3std', 'close_1hour_w10_ma_up_3std']},
         #{'volume' : [  'volume_1hour_w10_ma_low_2std', 'volume_1hour_w10_ma_up_2std', 'volume_1hour_w10_ma_low_3std', 'volume_1hour_w10_ma_up_3std']},
         #{'btc_close' : [  'btc_close_1hour_w10_ma_low_2std', 'btc_close_1hour_w10_ma_up_2std', 'btc_close_1hour_w10_ma_low_3std', 'btc_close_1hour_w10_ma_up_3std']},
        #w20
         {'close' : [  'close_1hour_w20_ma_low_2std', 'close_1hour_w20_ma_up_2std', 'close_1hour_w20_ma_low_3std', 'close_1hour_w20_ma_up_3std']},
         #{'btc_close' : [  'btc_close_1hour_w20_ma_low_2std', 'btc_close_1hour_w20_ma_up_2std', 'btc_close_1hour_w20_ma_low_3std', 'btc_close_1hour_w20_ma_up_3std']},
        #w30
         {'close' : [  'close_1hour_w30_ma_low_2std', 'close_1hour_w30_ma_up_2std', 'close_1hour_w30_ma_low_3std', 'close_1hour_w30_ma_up_3std']},
         #{'btc_close' : [  'btc_close_1hour_w30_ma_low_2std', 'btc_close_1hour_w30_ma_up_2std', 'btc_close_1hour_w30_ma_low_3std', 'btc_close_1hour_w30_ma_up_3std']},
        #w60
         {'close' : [  'close_1hour_w60_ma_low_2std', 'close_1hour_w60_ma_up_2std', 'close_1hour_w60_ma_low_3std', 'close_1hour_w60_ma_up_3std']},
         #{'btc_close' : [  'btc_close_1hour_w60_ma_low_2std', 'btc_close_1hour_w60_ma_up_2std', 'btc_close_1hour_w60_ma_low_3std', 'btc_close_1hour_w60_ma_up_3std']},
        #w120
         {'close' : [  'close_1hour_w120_ma_low_2std', 'close_1hour_w120_ma_up_2std', 'close_1hour_w120_ma_low_3std', 'close_1hour_w120_ma_up_3std']},
         #{'btc_close' : [  'btc_close_1hour_w120_ma_low_2std', 'btc_close_1hour_w120_ma_up_2std', 'btc_close_1hour_w120_ma_low_3std', 'btc_close_1hour_w120_ma_up_3std']},


        #w5
        ['close_1hour_w5_min', 'close_1hour_w5_max'],
        #['volume_1hour_w5_min', 'volume_1hour_w5_max'],
        #['btc_close_1hour_w5_min', 'btc_close_1hour_w5_max'],
        #w10
        ['close_1hour_w10_min', 'close_1hour_w10_max'],
        #['volume_1hour_w10_min', 'volume_1hour_w10_max'],
        #['btc_close_1hour_w10_min', 'btc_close_1hour_w10_max'],
        #w20
        ['close_1hour_w20_min', 'close_1hour_w20_max'],
        #['btc_close_1hour_w20_min', 'btc_close_1hour_w20_max'],
        #w30
        ['close_1hour_w30_min', 'close_1hour_w30_max'],
        #['btc_close_1hour_w30_min', 'btc_close_1hour_w30_max'],
        #w60
        ['close_1hour_w60_min', 'close_1hour_w60_max'],
        #['btc_close_1hour_w60_min', 'btc_close_1hour_w60_max'],
        #w120
        ['close_1hour_w120_min', 'close_1hour_w120_max'],
        #['btc_close_1hour_w120_min', 'btc_close_1hour_w120_max'],
]

In [185]:
groups_1day= [
        #windows: 
        #close: w1, w5, w10, w20, w30, w60, w120
        #volume: w1, w5, w10, w20
        #btc_close: w1, w5, w10, w20, w30, w60, w120
         ['close_1day_w1_roc', 'close_1day_w5_alpha', 'close_1day_w10_alpha', 'close_1day_w20_alpha', 'close_1day_w30_alpha', 'close_1day_w60_alpha', 'close_1day_w120_alpha'],
         #['volume_1day_w1_roc', 'volume_1day_w5_alpha', 'volume_1day_w10_alpha'],
         #['btc_close_1day_w1_roc', 'btc_close_1day_w5_alpha', 'btc_close_1day_w10_alpha', 'btc_close_1day_w20_alpha', 'btc_close_1day_w30_alpha', 'btc_close_1day_w60_alpha', 'btc_close_1day_w120_alpha'],
    
         ['close_1day_w1_roc', 'close_1day_w5_roc', 'close_1day_w10_roc', 'close_1day_w20_roc', 'close_1day_w30_roc', 'close_1day_w60_roc', 'close_1day_w120_roc'],
         #['volume_1day_w1_roc', 'volume_1day_w5_roc', 'volume_1day_w10_roc'],
         #['btc_close_1day_w1_roc', 'btc_close_1day_w5_roc', 'btc_close_1day_w10_roc', 'btc_close_1day_w20_roc', 'btc_close_1day_w30_roc', 'btc_close_1day_w60_roc', 'btc_close_1day_w120_roc'],

         ['close_1day_w5_mean_abs_pct', 'close_1day_w10_mean_abs_pct', 'close_1day_w20_mean_abs_pct', 'close_1day_w30_mean_abs_pct', 'close_1day_w60_mean_abs_pct', 'close_1day_w120_mean_abs_pct'],
         #['volume_1day_w5_mean_abs_pct', 'volume_1day_w10_mean_abs_pct'],
         #['btc_close_1day_w5_mean_abs_pct', 'btc_close_1day_w10_mean_abs_pct', 'btc_close_1day_w20_mean_abs_pct', 'btc_close_1day_w30_mean_abs_pct', 'btc_close_1day_w60_mean_abs_pct', 'btc_close_1day_w120_mean_abs_pct'],


         ['close_1day_w5_std', 'close_1day_w10_std', 'close_1day_w20_std', 'close_1day_w30_std', 'close_1day_w60_std', 'close_1day_w120_std'],
         #['volume_1day_w5_std', 'volume_1day_w10_std'],
         #['btc_close_1day_w5_std', 'btc_close_1day_w10_std', 'btc_close_1day_w20_std', 'btc_close_1day_w30_std', 'btc_close_1day_w60_std', 'btc_close_1day_w120_std'],


         ['close_1day_w5_norm_std', 'close_1day_w10_norm_std', 'close_1day_w20_norm_std', 'close_1day_w30_norm_std', 'close_1day_w60_norm_std', 'close_1day_w120_norm_std'],
         #['volume_1day_w5_norm_std', 'volume_1day_w10_norm_std'],
         #['btc_close_1day_w5_norm_std', 'btc_close_1day_w10_norm_std', 'btc_close_1day_w20_norm_std', 'btc_close_1day_w30_norm_std', 'btc_close_1day_w60_norm_std', 'btc_close_1day_w120_norm_std'],


         ['close_1day_w5_rsi', 'close_1day_w10_rsi', 'close_1day_w20_rsi', 'close_1day_w30_rsi', 'close_1day_w60_rsi', 'close_1day_w120_rsi'],
         #['volume_1day_w5_rsi', 'volume_1day_w10_rsi'],
         #['btc_close_1day_w5_rsi', 'btc_close_1day_w10_rsi', 'btc_close_1day_w20_rsi', 'btc_close_1day_w30_rsi', 'btc_close_1day_w60_rsi', 'btc_close_1day_w120_rsi'],


         ['close', 'close_1day_w5_ma', 'close_1day_w10_ma', 'close_1day_w20_ma', 'close_1day_w30_ma', 'close_1day_w60_ma', 'close_1day_w120_ma'],
         #['volume', 'volume_1day_w5_ma', 'volume_1day_w10_ma'],
         #['btc_close', 'btc_close_1day_w5_ma', 'btc_close_1day_w10_ma', 'btc_close_1day_w20_ma', 'btc_close_1day_w30_ma', 'btc_close_1day_w60_ma', 'btc_close_1day_w120_ma'],


         ['close', 'close_1day_w5_expma', 'close_1day_w10_expma', 'close_1day_w20_expma', 'close_1day_w30_expma', 'close_1day_w60_expma', 'close_1day_w120_expma'],
         #['volume', 'volume_1day_w5_expma', 'volume_1day_w10_expma',],
         #['btc_close', 'btc_close_1day_w5_expma', 'btc_close_1day_w10_expma', 'btc_close_1day_w20_expma', 'btc_close_1day_w30_expma', 'btc_close_1day_w60_expma', 'btc_close_1day_w120_expma'],


         {'close' : ['close_1day_w5_min', 'close_1day_w10_min', 'close_1day_w20_min', 'close_1day_w30_min', 'close_1day_w60_min', 'close_1day_w120_min']},
         #{'volume' : ['volume_1day_w5_min', 'volume_1day_w10_min',]},
         #{'btc_close' : ['btc_close_1day_w5_min', 'btc_close_1day_w10_min', 'btc_close_1day_w20_min', 'btc_close_1day_w30_min', 'btc_close_1day_w60_min', 'btc_close_1day_w120_min']},

    
         {'close' : ['close_1day_w5_max', 'close_1day_w10_max', 'close_1day_w20_max', 'close_1day_w30_max', 'close_1day_w60_max', 'close_1day_w120_max']},
         #{'volume' : ['volume_1day_w5_max', 'volume_1day_w10_max',]},
         #{'btc_close' : ['btc_close_1day_w5_max', 'btc_close_1day_w10_max', 'btc_close_1day_w20_max', 'btc_close_1day_w30_max', 'btc_close_1day_w60_max', 'btc_close_1day_w120_max']},



        #w5
         {'close' : [  'close_1day_w5_ma_low_2std', 'close_1day_w5_ma_up_2std', 'close_1day_w5_ma_low_3std', 'close_1day_w5_ma_up_3std']},
         #{'volume' : [  'volume_1day_w5_ma_low_2std', 'volume_1day_w5_ma_up_2std', 'volume_1day_w5_ma_low_3std', 'volume_1day_w5_ma_up_3std']},
         #{'btc_close' : [  'btc_close_1day_w5_ma_low_2std', 'btc_close_1day_w5_ma_up_2std', 'btc_close_1day_w5_ma_low_3std', 'btc_close_1day_w5_ma_up_3std']},
        #w10
         {'close' : [  'close_1day_w10_ma_low_2std', 'close_1day_w10_ma_up_2std', 'close_1day_w10_ma_low_3std', 'close_1day_w10_ma_up_3std']},
         #{'volume' : [  'volume_1day_w10_ma_low_2std', 'volume_1day_w10_ma_up_2std', 'volume_1day_w10_ma_low_3std', 'volume_1day_w10_ma_up_3std']},
         #{'btc_close' : [  'btc_close_1day_w10_ma_low_2std', 'btc_close_1day_w10_ma_up_2std', 'btc_close_1day_w10_ma_low_3std', 'btc_close_1day_w10_ma_up_3std']},
        #w20
         {'close' : [  'close_1day_w20_ma_low_2std', 'close_1day_w20_ma_up_2std', 'close_1day_w20_ma_low_3std', 'close_1day_w20_ma_up_3std']},
         #{'btc_close' : [  'btc_close_1day_w20_ma_low_2std', 'btc_close_1day_w20_ma_up_2std', 'btc_close_1day_w20_ma_low_3std', 'btc_close_1day_w20_ma_up_3std']},
        #w30
         {'close' : [  'close_1day_w30_ma_low_2std', 'close_1day_w30_ma_up_2std', 'close_1day_w30_ma_low_3std', 'close_1day_w30_ma_up_3std']},
         #{'btc_close' : [  'btc_close_1day_w30_ma_low_2std', 'btc_close_1day_w30_ma_up_2std', 'btc_close_1day_w30_ma_low_3std', 'btc_close_1day_w30_ma_up_3std']},
        #w60
         {'close' : [  'close_1day_w60_ma_low_2std', 'close_1day_w60_ma_up_2std', 'close_1day_w60_ma_low_3std', 'close_1day_w60_ma_up_3std']},
         #{'btc_close' : [  'btc_close_1day_w60_ma_low_2std', 'btc_close_1day_w60_ma_up_2std', 'btc_close_1day_w60_ma_low_3std', 'btc_close_1day_w60_ma_up_3std']},
        #w120
         {'close' : [  'close_1day_w120_ma_low_2std', 'close_1day_w120_ma_up_2std', 'close_1day_w120_ma_low_3std', 'close_1day_w120_ma_up_3std']},
         #{'btc_close' : [  'btc_close_1day_w120_ma_low_2std', 'btc_close_1day_w120_ma_up_2std', 'btc_close_1day_w120_ma_low_3std', 'btc_close_1day_w120_ma_up_3std']},


        #w5
        ['close_1day_w5_min', 'close_1day_w5_max'],
        #['volume_1day_w5_min', 'volume_1day_w5_max'],
        #['btc_close_1day_w5_min', 'btc_close_1day_w5_max'],
        #w10
        ['close_1day_w10_min', 'close_1day_w10_max'],
        #['volume_1day_w10_min', 'volume_1day_w10_max'],
        #['btc_close_1day_w10_min', 'btc_close_1day_w10_max'],
        #w20
        ['close_1day_w20_min', 'close_1day_w20_max'],
        #['btc_close_1day_w20_min', 'btc_close_1day_w20_max'],
        #w30
        ['close_1day_w30_min', 'close_1day_w30_max'],
        #['btc_close_1day_w30_min', 'btc_close_1day_w30_max'],
        #w60
        ['close_1day_w60_min', 'close_1day_w60_max'],
        #['btc_close_1day_w60_min', 'btc_close_1day_w60_max'],
        #w120
        ['close_1day_w120_min', 'close_1day_w120_max'],
        #['btc_close_1day_w120_min', 'btc_close_1day_w120_max'],
]

In [187]:
def uniq_pairs(cols):
    pairs = []
    for i in range(len(cols)-1):
        for j in range(i+1, len(cols)):
            pairs += [(cols[i], cols[j])]
    return pairs

def calc_relative_features(df, groups):
    for group in tqdm(groups):
        if type(group) == list:
            pairs = uniq_pairs(group)
            for pair in pairs:
                new_col = f'{pair[0]}/{pair[1]}'
                df[new_col] = df[pair[0]] / (df[pair[1]] + np.finfo(np.float32).eps)

        if type(group) == dict:
            pair1 = list(group.keys())[0]
            for pair0 in group[pair1]:
                new_col = f'{pair0}/{pair1}'
                df[new_col] = df[pair0] / (df[pair1] + np.finfo(np.float32).eps)

    return df

In [188]:
import warnings
warnings.filterwarnings('ignore')

In [190]:
print(df.shape)
calc_relative_features(df, groups_5min)
df.shape

(129312, 339)

100%|████████████████████████████████████████████████████████████████████████| 22/22 [00:00<00:00, 454.20it/s]

(129312, 525)

In [192]:
print(df.shape)
calc_relative_features(df, groups_1hour)
df.shape

(129312, 525)

100%|████████████████████████████████████████████████████████████████████████| 22/22 [00:00<00:00, 505.52it/s]

(129312, 711)

In [194]:
print(df.shape)
calc_relative_features(df, groups_1day)
df.shape

(129312, 711)

100%|████████████████████████████████████████████████████████████████████████| 22/22 [00:00<00:00, 517.17it/s]

(129312, 897)

In [197]:
# for col in tqdm(df.columns):
#     assert df[col].isnull().sum() == 0, f'Nulls {col}'

### Delete absolute valu columns

In [200]:
len(cols_del_5min), len(cols_del_1hour), len(cols_del_1day)

(54, 54, 54)

In [201]:
print(df.shape)
for col in cols_del_5min+cols_del_1hour+cols_del_1day:
    del df[col]
df.shape

(129312, 897)

(129312, 735)

## 2.6 Save data

In [207]:
!mkdir data/feat_engin/lgbm

mkdir: data/feat_engin/lgbm: File exists

In [208]:
#save
dump_pkl(df, 'data/feat_engin/lgbm/data_5min_1hour_1day.pkl')

In [209]:
df.shape

(129312, 735)

In [210]:
df.head()

,time,close,ticker,index_1hour,index_1day,close_w1_roc,close_w5_norm_std,close_w5_mean_abs_pct,close_w5_alpha,close_w5_rsi,...,close_1day_w120_ma_low_2std/close,close_1day_w120_ma_up_2std/close,close_1day_w120_ma_low_3std/close,close_1day_w120_ma_up_3std/close,close_1day_w5_min/close_1day_w5_max,close_1day_w10_min/close_1day_w10_max,close_1day_w20_min/close_1day_w20_max,close_1day_w30_min/close_1day_w30_max,close_1day_w60_min/close_1day_w60_max,close_1day_w120_min/close_1day_w120_max
0,2024-01-01 00:00:00,0.616573,TON-NEAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-01-01 00:05:00,0.616427,TON-NEAR,NaN,NaN,-0.000237,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-01-01 00:10:00,0.613775,TON-NEAR,NaN,NaN,-0.004303,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-01-01 00:15:00,0.608855,TON-NEAR,NaN,NaN,-0.008015,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-01-01 00:20:00,0.609961,TON-NEAR,NaN,NaN,0.001816,0.00585,NaN,-404.119354,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [212]:
#df.columns.tolist()

In [215]:
no_features = [
 'time',
 'close',
 'volume',
 'btc_close',

 'ticker',

 'index_1hour',
 'index_1day',
 'result',
 'delta_time',
 'income_rate',
 'res_price',
 'res_ind',

'time_1hour',
 'close_1hour',
 'volume_1hour',
 'btc_close_1hour',

'time_1day',
 'close_1day',
 'volume_1day',
 'btc_close_1day',]

### 2.7 Save data to NN

In [217]:
#don't use NN

In [219]:
# df_fe.head()

In [220]:
# df_1day_fe.head()

In [221]:
# df_fe.shape, df_1day_fe.shape

In [222]:
# dump_pkl(df_fe, 'data/feat_engin/lgbm/data_1hour.pkl')
# dump_pkl(df_1day_fe, 'data/feat_engin/lgbm/data_1day.pkl')

# TMP

In [225]:
import numpy as np
import pandas as pd
from tqdm import tqdm
import random
import matplotlib.pyplot as plt
import seaborn as sns
import datetime
import os

from sklearn.metrics import roc_auc_score

import pickle
def dump_pkl(data, filename):
  with open(filename, 'wb') as handle:
    pickle.dump(data, handle, protocol=pickle.HIGHEST_PROTOCOL)

def load_pkl(filename):
  with open(filename, 'rb') as handle:
    data = pickle.load(handle)
  return data

In [226]:
df = load_pkl('data/feat_engin/lgbm/data_5min_1hour_1day.pkl')

In [227]:
df

,time,close,ticker,index_1hour,index_1day,close_w1_roc,close_w5_norm_std,close_w5_mean_abs_pct,close_w5_alpha,close_w5_rsi,...,close_1day_w120_ma_low_2std/close,close_1day_w120_ma_up_2std/close,close_1day_w120_ma_low_3std/close,close_1day_w120_ma_up_3std/close,close_1day_w5_min/close_1day_w5_max,close_1day_w10_min/close_1day_w10_max,close_1day_w20_min/close_1day_w20_max,close_1day_w30_min/close_1day_w30_max,close_1day_w60_min/close_1day_w60_max,close_1day_w120_min/close_1day_w120_max
0,2024-01-01 00:00:00,0.616573,TON-NEAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-01-01 00:05:00,0.616427,TON-NEAR,NaN,NaN,-0.000237,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-01-01 00:10:00,0.613775,TON-NEAR,NaN,NaN,-0.004303,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-01-01 00:15:00,0.608855,TON-NEAR,NaN,NaN,-0.008015,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-01-01 00:20:00,0.609961,TON-NEAR,NaN,NaN,0.001816,0.005850,NaN,-404.119354,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129307,2025-03-24 23:35:00,1.255537,TON-NEAR,10774.0,447.0,0.000415,0.001530,0.001250,-728.287720,42.613983,...,0.662326,1.024601,0.571758,1.115169,0.967858,0.81449,0.720836,0.715516,0.715516,0.614914
129308,2025-03-24 23:40:00,1.256227,TON-NEAR,10774.0,447.0,0.000549,0.000867,0.000910,-664.997192,21.176495,...,0.661963,1.024038,0.571444,1.114557,0.967858,0.81449,0.720836,0.715516,0.715516,0.614914
129309,2025-03-24 23:45:00,1.255036,TON-NEAR,10774.0,447.0,-0.000948,0.000393,0.000827,246.021439,23.296997,...,0.662591,1.025010,0.571986,1.115614,0.967858,0.81449,0.720836,0.715516,0.715516,0.614914
129310,2025-03-24 23:50:00,1.255464,TON-NEAR,10774.0,447.0,0.000342,0.000392,0.000531,409.433197,49.144466,...,0.662364,1.024660,0.571791,1.115233,0.967858,0.81449,0.720836,0.715516,0.715516,0.614914
129311,2025-03-24 23:55:00,1.254862,TON-NEAR,10775.0,447.0,-0.000480,0.000422,0.000547,-1876.875244,47.764801,...,0.662683,1.025152,0.572065,1.115769,0.967858,0.81449,0.720836,0.715516,0.715516,0.614914

#### uniq_1

In [230]:
no_analyze = [
 'time',
 # 'close',
 #'volume',
 #'btc_close',

 'ticker',

 #'index_1hour',
 #'index_1day',
 'result',
 'delta_time',
 #'income_rate',
 #'res_price',
 #'res_ind',

 'time_1hour',
 #'close_1hour',
 #'volume_1hour',
 #'btc_close_1hour',

 'time_1day',
 #'close_1day',
 #'volume_1day',
 #'btc_close_1day',
]

In [232]:
# df_tmp = df[df.columns[~df.columns.isin(no_analyze)]].mean().reset_index()

df_tmp = []
for col in tqdm(df.columns[~df.columns.isin(no_analyze)]):
    df_tmp += [df[col].mean()]

df_tmp = pd.DataFrame({'index' : df.columns[~df.columns.isin(no_analyze)],
                      0 : df_tmp})

df_tmp

100%|█████████████████████████████████████████████████████████████████████| 731/731 [00:00<00:00, 4088.21it/s]

                                       index            0
0                                      close     1.031050
1                                index_1hour  5387.041670
2                                 index_1day   223.439355
3                               close_w1_roc     0.000011
4                          close_w5_norm_std     0.002532
..                                       ...          ...
726    close_1day_w10_min/close_1day_w10_max     0.840832
727    close_1day_w20_min/close_1day_w20_max     0.761115
728    close_1day_w30_min/close_1day_w30_max     0.711951
729    close_1day_w60_min/close_1day_w60_max     0.615071
730  close_1day_w120_min/close_1day_w120_max     0.498719

[731 rows x 2 columns]

In [233]:
df_tmp[df_tmp[0].isnull()]

Empty DataFrame
Columns: [index, 0]
Index: []

In [234]:
df_tmp.groupby(0).index.unique()[df_tmp.groupby(0).index.nunique()>1]

0
1.00016    [close_w60_ma/close_w120_ma, close_1hour_w5_ma...
Name: index, dtype: object

In [235]:
df_tmp.groupby(0).index.unique()[df_tmp.groupby(0).index.nunique()>1].values

array([array(['close_w60_ma/close_w120_ma',
              'close_1hour_w5_ma/close_1hour_w10_ma'], dtype=object)],
      dtype=object)

In [ ]:
#df[['volume/volume_1hour_w5_ma', 'volume/volume_1hour_w5_expma']]

#### uniq_2

In [235]:
#df_tmp = df[df.columns[~df.columns.isin(no_analyze)]].nunique().reset_index()

df_tmp = []
for col in tqdm(df.columns[~df.columns.isin(no_analyze)]):
    df_tmp += [df[col].nunique()]

df_tmp = pd.DataFrame({'index' : df.columns[~df.columns.isin(no_analyze)],
                      0 : df_tmp})

df_tmp

100%|██████████████████████████████████████████████████████████████████████| 731/731 [00:01<00:00, 554.99it/s]

                                       index       0
0                                      close  253851
1                                index_1hour   23256
2                                 index_1day     968
3                               close_w1_roc  260910
4                          close_w5_norm_std  276811
..                                       ...     ...
726    close_1day_w10_min/close_1day_w10_max     599
727    close_1day_w20_min/close_1day_w20_max     443
728    close_1day_w30_min/close_1day_w30_max     383
729    close_1day_w60_min/close_1day_w60_max     267
730  close_1day_w120_min/close_1day_w120_max     180

[731 rows x 2 columns]

In [237]:
df_tmp[df_tmp[0].isnull()]

Empty DataFrame
Columns: [index, 0]
Index: []

In [239]:
pd.set_option('display.max_rows', 120)
df_tmp.groupby(0).index.unique()[df_tmp.groupby(0).index.nunique()>1].reset_index()

         0                                              index
0        8  [close_1day_w30_lvl_1.08-1.1, close_1day_w30_l...
1        9  [close_1day_w30_lvl_1.02-1.04, close_1day_w30_...
2       10  [close_1day_w30_lvl_-0.98-1, close_1day_w30_lv...
3       11  [close_1day_w30_lvl_1-1.02, close_1day_w30_lvl...
4       18  [close_1day_w120_lvl_1.02-1.04, close_1day_w12...
5       19  [close_1hour_w30_lvl_1.1-1.12, close_1day_w120...
6       20  [close_w30_lvl_-0.88-0.9, close_1hour_w30_lvl_...
7       21  [close_1day_w120_lvl_-0.96-0.98, close_1day_w1...
8       22  [close_w30_lvl_1.08-1.1, close_w30_lvl_1.1-1.1...
9       23  [close_w30_lvl_-0.9-0.92, close_1hour_w30_lvl_...
10      24  [hour, close_1hour_w30_lvl_1.06-1.08, close_1d...
11      26  [close_w30_lvl_1.06-1.08, close_1hour_w30_lvl_...
12      28  [close_w30_lvl_-0.92-0.94, close_1hour_w30_lvl...
13      30  [close_w30_lvl_1-1.02, close_w30_lvl_-0.98-1, ...
14      60  [close_1hour_w120_lvl_1.06-1.08, close_1hour_w...
15     120  [close_w120_lvl_1-1.02, close_w120_lvl_-0.98-1...
16     848  [close_1day_w120_mean_abs_pct, close_1day_w120...
17     849  [close_1day_w120_norm_std, close_1day_w120_alp...
18     908  [close_1day_w60_mean_abs_pct, close_1day_w60_r...
19     909  [close_1day_w60_norm_std, close_1day_w60_alpha...
20     938  [close_1day_w30_mean_abs_pct, close_1day_w30_r...
21     939  [close_1day_w30_norm_std, close_1day_w30_alpha...
22     948  [close_1day_w20_mean_abs_pct, close_1day_w20_r...
23     949  [close_1day_w20_norm_std, close_1day_w20_alpha...
24     958  [close_1day_w10_norm_std, close_1day_w10_mean_...
25     959  [close_1day_w10_alpha, close_1day_w1_roc/close...
26     963  [close_1day_w5_mean_abs_pct, close_1day_w5_roc...
27     964  [close_1day_w5_norm_std, close_1day_w5_alpha, ...
28     968                           [index_1day, close_1day]
29   23113  [close_1hour_w5_mean_abs_pct/close_1hour_w120_...
30   23116  [close_1hour_w120_mean_abs_pct, close_1hour_w2...
31   23119  [close_1hour_w5_roc/close_1hour_w120_roc, clos...
32   23122  [close_1hour_w5_norm_std/close_1hour_w120_norm...
33   23123  [close_1hour_w60_std/close_1hour_w120_std, clo...
34   23124  [close_1hour_w20_std/close_1hour_w120_std, clo...
35   23126  [close_1hour_w10_roc/close_1hour_w120_roc, clo...
36   23128  [close_1hour_w120_norm_std, close_1hour_w120_r...
37   23133  [close_1hour_w30_alpha/close_1hour_w120_alpha,...
38   23134  [close_1hour_w20_alpha/close_1hour_w120_alpha,...
39   23167  [close_1hour_w1_roc/close_1hour_w60_alpha, clo...
40   23177  [close_1hour_w5_mean_abs_pct/close_1hour_w60_m...
41   23178  [close_1hour_w5_roc/close_1hour_w60_roc, close...
42   23182  [close_1hour_w5_std/close_1hour_w60_std, close...
43   23186  [close_1hour_w30_std/close_1hour_w60_std, clos...
44   23188  [close_1hour_w10_alpha/close_1hour_w60_alpha, ...
45   23193  [close_1hour_w30_rsi, close_1hour_w20_alpha/cl...
46   23194  [close_1hour_w60_alpha, close_1hour_w5_alpha/c...
47   23196  [close_1hour_w1_roc/close_1hour_w30_roc, close...
48   23198  [close_1hour_w1_roc/close_1hour_w30_alpha, clo...
49   23202  [close_1hour_w10_norm_std/close_1hour_w30_norm...
50   23206  [close_1hour_w30_mean_abs_pct, close_1hour_w1_...
51   23207  [close_1hour_w1_roc/close_1hour_w20_alpha, clo...
52   23209  [close_1hour_w5_mean_abs_pct/close_1hour_w10_m...
53   23213  [close_1hour_w20_rsi, close_1hour_w5_std/close...
54   23219  [close_1hour_w1_roc/close_1hour_w10_alpha, clo...
55   23222  [close_1hour_w10_alpha/close_1hour_w30_alpha, ...
56   23224  [close_1hour_w30_alpha, close_1hour_w30_roc, c...
57   23225  [close_1hour_w5_norm_std, close_1hour_w5_roc, ...
58   23228  [close_1hour_w20_norm_std, close_1hour_w10_alp...
59   23236  [close_1hour_w10_roc, close_1hour_w5_alpha/clo...
60   23240      [close_1hour_w5_alpha, close_1hour_w10_alpha]
61  232284  [close_1day_w120_ma_up_2std/close, close_1day_...
62  232285  [close_1day_w120_ma_low_2std/close, close_1day...
63  247970  [close/close_1day_w60_expma, close_1day_w60_ma...
64  247974  [close_1day_w60_ma_low_2std/close, close_1day_...
65  256151  [close/close_1day_w30_ma, close_1day_w30_ma_up...
66  258982  [close/close_1day_w20_expma, close_1day_w20_ma...
67  258983  [close/close_1day_w20_ma, close_1day_w20_ma_up...
68  258985  [close_1day_w20_ma_low_2std/close, close_1day_...
69  261828  [close/close_1day_w10_ma, close/close_1day_w10...
70  261833  [close_1day_w10_ma_low_2std/close, close_1day_...
71  270577  [close_1hour_w120_ma_low_2std/close, close_1ho...
72  271292  [close_1hour_w60_ma_up_2std/close, close_1hour...
73  271293  [close/close_1hour_w60_expma, close_1hour_w60_...
74  271652  [close/close_1hour_w30_expma, close_1hour_w30_...
75  271769  [close_1hour_w20_ma_up_2std/close, close_1hour...
76  271771  [close/close_1hour_w20_ma, close/close_1hour_w...
77  271772  [close_1hour_w20_ma_low_2std/close, close_1hou...
78  271887  [close/close_1hour_w10_ma, close_1hour_w10_ma_...
79  271938  [close_1hour_w5_ma_low_3std/close, close_1hour...
80  277010  [close_w10_norm_std/close_w30_norm_std, close_...
81  277351  [close_w5_std/close_w30_std, close_w10_std/clo...
82  278865  [close_w5_ma_low_2std/close, close_w5_ma_up_3s...
83  278911  [close_w10_ma_low_2std/close, close_w10_ma_up_...
84  278915  [close_w60_ma_up_2std/close, close_w60_ma_up_3...
85  278916  [close/close_w5_expma, close_w120_ma_up_2std/c...
86  278917  [close/close_w60_ma, close_w60_ma_low_3std/clo...
87  278918  [close/close_w120_ma, close_w120_ma_low_3std/c...
88  278919  [close/close_w20_ma, close_w60_ma_low_2std/close]
89  278922  [close/close_w30_ma, close_w20_ma_low_3std/close]
90  278923  [close_w20_ma_up_2std/close, close_w20_ma_up_3...
91  278924  [close_w30_ma_up_2std/close, close_w30_ma_up_3...
92  278942     [close/close_w10_expma, close/close_w30_expma]

In [242]:
i = 43
df_tmp.groupby(0).index.unique()[df_tmp.groupby(0).index.nunique()>1].index[i], df_tmp.groupby(0).index.unique()[df_tmp.groupby(0).index.nunique()>1].iloc[i]

(23186,
 array(['close_1hour_w30_std/close_1hour_w60_std',
        'close_1hour_w20_rsi/close_1hour_w30_rsi'], dtype=object))

In [246]:
np.sort(df['close_1day_w120_mean_abs_pct'].unique())

array([0.02613296, 0.02673005, 0.02673106, 0.02677331, 0.02678873,
       0.02681054, 0.02683949, 0.02684634, 0.02685287, 0.02687069,
       0.02689086, 0.02690207, 0.02693679, 0.02696653, 0.02698202,
       0.02698792, 0.02700364, 0.02700917, 0.02701527, 0.02704694,
       0.02705433, 0.02705506, 0.02705899, 0.02707405, 0.02708023,
       0.0270848 , 0.02709831, 0.02710364, 0.02713189, 0.02714841,
       0.02714849, 0.02715299, 0.02718076, 0.02718794, 0.02719436,
       0.02719866, 0.0272035 , 0.02721307, 0.02721904, 0.02723946,
       0.02726167, 0.02726268, 0.02727352, 0.02727564, 0.02727604,
       0.02728847, 0.02729654, 0.02730343, 0.02730386, 0.02731231,
       0.0273164 , 0.02731901, 0.02732269, 0.02732275, 0.02734269,
       0.0273437 , 0.02734951, 0.02736937, 0.02738471, 0.02739167,
       0.0273951 , 0.02739844, 0.02746778, 0.02751391, 0.02752998,
       0.02754103, 0.02756708, 0.02758695, 0.02760189, 0.02760641,
       0.02763933, 0.02769764, 0.02772624, 0.02772642, 0.02774439,
       0.02778639, 0.02782187, 0.0278302 , 0.02783661, 0.02787188,
       0.02789534, 0.02793795, 0.02799651, 0.02805151, 0.0281594 ,
       0.02816268, 0.02829835, 0.02829967, 0.02831197, 0.02831486,
       0.02832704, 0.02834736, 0.02835876, 0.02838834, 0.02846044,
       0.02847743, 0.02848066, 0.02848119, 0.02848242, 0.02851824,
       0.02852425, 0.02865471, 0.0286684 , 0.02870697, 0.02881009,
       0.0288124 , 0.02889881, 0.02893091, 0.0289359 , 0.02894566,
       0.02899235, 0.02899893, 0.02899977, 0.02903291, 0.02903725,
       0.02906331, 0.02908323, 0.0290836 , 0.02911041, 0.02913349,
       0.02915799, 0.02920278, 0.02920846, 0.02922646, 0.02923042,
       0.02925031, 0.02925128, 0.02929538, 0.02936096, 0.02936476,
       0.02937501, 0.02938467, 0.02945261, 0.02946584, 0.02948596,
       0.02950254, 0.02951638, 0.0295248 , 0.02954061, 0.02954577,
       0.02959824, 0.02963603, 0.02964234, 0.02968837, 0.02970925,
       0.02972043, 0.02972757, 0.02973307, 0.02973874, 0.02976038,
       0.02980285, 0.02982775, 0.02987194, 0.02989714, 0.02991918,
       0.02994841, 0.02995922, 0.02996169, 0.02998636, 0.02999204,
       0.03002414, 0.03002813, 0.03005736, 0.03011142, 0.03017724,
       0.03021193, 0.03024257, 0.03030026, 0.03032017, 0.03032854,
       0.03033455, 0.03034098, 0.03035187, 0.03035558, 0.03036712,
       0.03041313, 0.03041515, 0.03041567, 0.03041874, 0.03042737,
       0.03043624, 0.03044571, 0.0304531 , 0.03045477, 0.03045477,
       0.03045979, 0.03047742, 0.0304827 , 0.03049893, 0.03052557,
       0.03054822, 0.0305736 , 0.03060926, 0.03064195, 0.03072727,
       0.03075433, 0.03082515, 0.03084848, 0.03085055, 0.03086697,
       0.03087065, 0.03087826, 0.03091423, 0.03092762, 0.03094023,
       0.0309421 , 0.03094383, 0.03094398, 0.03105056, 0.03120499,
       0.03122736, 0.03144782, 0.03152821, 0.03159426, 0.03163655,
       0.03170428, 0.03175014, 0.0317728 , 0.03177319, 0.03179579,
       0.03184802, 0.03184899, 0.03186179, 0.03186882, 0.03188127,
       0.03191301, 0.03193265, 0.032002  , 0.03202188, 0.03203557,
       0.03203993, 0.03204212, 0.03207589, 0.0320913 , 0.0321052 ,
       0.03212873, 0.03215061, 0.03215181, 0.03215732, 0.03216378,
       0.03216617, 0.03218783, 0.03220814, 0.0322197 , 0.03226367,
       0.03227   , 0.0322757 , 0.03230605, 0.03237707, 0.03237988,
       0.03238056, 0.0324438 , 0.03247471, 0.03249385, 0.0325054 ,
       0.03251867, 0.03254947, 0.03262807, 0.03263346, 0.03269942,
       0.03270127, 0.03274449, 0.03274837, 0.03275745, 0.03276242,
       0.03276355, 0.03279812, 0.03279848, 0.03284613, 0.03297039,
       0.03297304, 0.03306631, 0.0331513 , 0.03317417, 0.03320704,
       0.0333111 , 0.03336149, 0.03336269, 0.03344495, 0.03344565,
       0.03346371, 0.0334766 , 0.03349859, 0.0335223 , 0.03359088,
       0.03360926, 0.03362162, 0.03362219, 0.03375817, 0.03377489,
       0.03383908, 0.03384461, 0.03384537, 0.03385041, 0.03387115,
       0.03388192, 0.03390137, 0.03390395, 0.0339125 , 0.03396165,
       0.03396681, 0.03396755, 0.03401319, 0.03404539, 0.03405261,
       0.03405306, 0.03406209, 0.03410133, 0.03414131, 0.03414316,
       0.03416185, 0.03417131, 0.03426131, 0.03427079, 0.03427317,
       0.03428164, 0.03428335, 0.03429746, 0.03430202, 0.03432138,
       0.03433811, 0.0343545 , 0.03438946, 0.03439058, 0.03439787,
       0.03444232, 0.03444707, 0.03446969, 0.03448127, 0.03449983,
       0.03454412, 0.03454451, 0.03455479, 0.03455933, 0.03458134,
       0.03466303, 0.0346886 , 0.03471696, 0.03472928, 0.03473153,
       0.03473796, 0.03474671, 0.03485586, 0.03491021, 0.0349112 ,
       0.03492621, 0.03495924, 0.03500417, 0.03501558, 0.03502312,
       0.03503459, 0.0350442 , 0.03517424, 0.03519873, 0.03521331,
       0.03524722, 0.03525231, 0.03525836, 0.03527566, 0.03528964,
       0.03531939, 0.03532735, 0.03532831, 0.03533062, 0.0353642 ,
       0.0353659 , 0.03537817, 0.03537856, 0.03539242, 0.03539948,
       0.03541394, 0.03541547, 0.03541981, 0.03542807, 0.03544406,
       0.03546664, 0.03547017, 0.03547486, 0.03550701, 0.03551589,
       0.03551865, 0.03552175, 0.03557343, 0.0355852 , 0.03558902,
       0.03559465, 0.03562896, 0.0356393 , 0.03564203, 0.03565072,
       0.03568223, 0.03580486, 0.03583181, 0.03584589, 0.03585013,
       0.03587092, 0.0358759 , 0.03591641, 0.03592262, 0.03594116,
       0.03595842, 0.03601805, 0.03607529, 0.03607672, 0.03608587,
       0.03612355, 0.03612632, 0.03613118, 0.03622744, 0.03624579,
       0.03625775, 0.03630688, 0.03631816, 0.03633705, 0.03641548,
       0.03642464, 0.03644457, 0.03647017, 0.03647446, 0.03651839,
       0.03652308, 0.03654745, 0.03654782, 0.03656227, 0.03662677,
       0.03664201, 0.03664637, 0.03666378, 0.03672136, 0.03672243,
       0.03673455, 0.03674068, 0.03677928, 0.03681605, 0.03682198,
       0.03683012, 0.03683406, 0.03683839, 0.03687977, 0.03688564,
       0.03688937, 0.03689835, 0.03694155, 0.03694192, 0.0369566 ,
       0.036992  , 0.03706104, 0.03709853, 0.03711285, 0.03739215,
       0.03741389, 0.0374152 , 0.03767901, 0.03769453, 0.03776524,
       0.03783407, 0.03787517, 0.03788534, 0.03793282, 0.03793671,
       0.0380393 , 0.03805106, 0.03805749, 0.03805818, 0.0380891 ,
       0.03816085, 0.03816985, 0.03822592, 0.03825726, 0.03841044,
       0.03842344, 0.03843589, 0.03843849, 0.03856214, 0.03857001,
       0.03863322, 0.03865619, 0.0386872 , 0.03874281, 0.03879362,
       0.03882985, 0.03887045, 0.0389444 , 0.03900659, 0.03901087,
       0.03910678, 0.03917167, 0.03921771, 0.03928972, 0.03936312,
       0.03939565, 0.03940209, 0.03952681, 0.03964522, 0.03970814,
       0.03972346, 0.0397369 , 0.0398137 , 0.03983728, 0.03988379,
       0.03990201, 0.03990405, 0.03991819, 0.04003132, 0.04004606,
       0.0400561 , 0.04007552, 0.04010687, 0.04012573, 0.04015485,
       0.04017634, 0.04019012, 0.04025358, 0.04026487, 0.04027066,
       0.04028069, 0.04036321, 0.04045006, 0.04047682, 0.04048263,
       0.04051995, 0.04066226, 0.04066894, 0.04068549, 0.04068732,
       0.04073668, 0.04081634, 0.0408165 , 0.04082249, 0.04093127,
       0.04099915, 0.04100508, 0.04102824, 0.04105763, 0.04106455,
       0.04108566, 0.04116151, 0.04120994, 0.04122384, 0.04123045,
       0.04124299, 0.04125264, 0.041274  , 0.0412756 , 0.04127961,
       0.04132992, 0.04135748, 0.04139884, 0.0414415 , 0.0414716 ,
       0.04148267, 0.04148735, 0.04150179, 0.0415289 , 0.04153803,
       0.04154661, 0.0415497 , 0.04155047, 0.04156329, 0.04164591,
       0.04164692, 0.04168105, 0.04168747, 0.04169485, 0.04170104,
       0.0417225 , 0.04174807, 0.0417483 , 0.04174969, 0.04175381,
       0.04176287, 0.04176664, 0.0417694 , 0.04178824, 0.04179168,
       0.04181064, 0.04181068, 0.04182081, 0.04184113, 0.04185863,
       0.04186241, 0.04186685, 0.04191166, 0.04193967, 0.04195235,
       0.04195413, 0.04195685, 0.04198128, 0.04202654, 0.04202657,
       0.04202887, 0.04203172, 0.04203504, 0.04203917, 0.04204199,
       0.04204798, 0.04207451, 0.04211667, 0.0421415 , 0.04217558,
       0.0422    , 0.04220195, 0.04222501, 0.04223941, 0.04225188,
       0.04229072, 0.04229231, 0.0423155 , 0.04231754, 0.04233504,
       0.04239587, 0.04242611, 0.0424437 , 0.04245656, 0.04246783,
       0.04246886, 0.04248247, 0.042494  , 0.04249551, 0.04249873,
       0.04250074, 0.04253157, 0.04255652, 0.0425683 , 0.04256905,
       0.04257142, 0.04260155, 0.04262509, 0.04262913, 0.04263986,
       0.04265657, 0.04269082, 0.04273262, 0.04273593, 0.04277815,
       0.04281419, 0.04282843, 0.04288653, 0.04292148, 0.04294717,
       0.04296018, 0.04298105, 0.04298395, 0.04299121, 0.04299158,
       0.04299292, 0.04299659, 0.04308102, 0.04308188, 0.04312657,
       0.04314876, 0.0431676 , 0.04318722, 0.04319184, 0.04323677,
       0.04324535, 0.04325143, 0.04329389, 0.04335498, 0.04335859,
       0.04337867, 0.04338567, 0.04338651, 0.0433985 , 0.04341664,
       0.04343061, 0.04343794, 0.04344133, 0.04344956, 0.04346932,
       0.04349556, 0.0434993 , 0.04351874, 0.0435245 , 0.04354873,
       0.04355782, 0.04356146, 0.04357477, 0.04357877, 0.04359767,
       0.04364513, 0.04365081, 0.0436573 , 0.043708  , 0.0437535 ,
       0.04376249, 0.04377654, 0.04378019, 0.04381483, 0.04382013,
       0.04385358, 0.04388968, 0.04392585, 0.04394814, 0.04395707,
       0.0439903 , 0.04401288, 0.04404235, 0.04414912, 0.04421648,
       0.04422355, 0.04427383, 0.04428583, 0.04432241, 0.0443254 ,
       0.04433765, 0.04438781, 0.04438891, 0.04444106, 0.04444119,
       0.04445436, 0.04447839, 0.04449414, 0.04453827, 0.04457154,
       0.04458899, 0.04460879, 0.0446687 , 0.04468673, 0.04471954,
       0.04472435, 0.04473068, 0.04474862, 0.04478756, 0.04481896,
       0.04481936, 0.04483682, 0.04484029, 0.04486956, 0.04491122,
       0.04492087, 0.04494637, 0.0449577 , 0.04496177, 0.04499234,
       0.04499716, 0.04503696, 0.04507286, 0.04509253, 0.04514084,
       0.04517354, 0.04519188, 0.04521598, 0.0452877 , 0.04532273,
       0.04535166, 0.04536942, 0.04541016, 0.04543259, 0.04543365,
       0.04543592, 0.04545591, 0.04560125, 0.04578091, 0.04580135,
       0.04580467, 0.04582257, 0.04582472, 0.04583737, 0.04585299,
       0.04586056, 0.04588012, 0.04588887, 0.04589137, 0.04589283,
       0.04592809, 0.04594008, 0.04598337, 0.04598569, 0.04599888,
       0.04603941, 0.04605043, 0.04606736, 0.04610847, 0.04619399,
       0.04623447, 0.04624637, 0.0462931 , 0.04631526, 0.0463832 ,
       0.04641719, 0.04643104, 0.04645466, 0.04645554, 0.04648364,
       0.04648892, 0.04662405, 0.04662431, 0.04665689, 0.04670897,
       0.04674782, 0.04676061, 0.04686384, 0.04702989, 0.04705542,
       0.04705634, 0.04710299, 0.04712351, 0.04715655, 0.04717486,
       0.04721654, 0.04722352, 0.04722919, 0.04724584, 0.04726376,
       0.04726469, 0.04732835, 0.04733349, 0.0473402 , 0.04734573,
       0.04736082, 0.04740681, 0.04742489, 0.04746716, 0.04747665,
       0.0474863 , 0.04750868, 0.04753471, 0.04753653, 0.04756989,
       0.0475876 , 0.0475951 , 0.04764775, 0.04765007, 0.04771678,
       0.04775156, 0.04781616, 0.04781728, 0.04783748, 0.0478811 ,
       0.04806945, 0.04810302, 0.04815201, 0.04817848, 0.04835154,
       0.04839432, 0.04848054, 0.04848616, 0.04862946, 0.04863899,
       0.04895661, 0.0489754 , 0.04897852, 0.04915772, 0.04920127,
       0.04945662, 0.04950967, 0.04965112,        nan], dtype=float32)